// Kronikan (Codex) käännös (de). Avaimet vastaavat Codex.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.back": "Zurück zum Spiel",
  "ui.rulebook": "Regelbuch",
  "ui.eyebrow": "Geschichten der Steppe",
  "ui.title": "Die Chronik der Grenzlande",
  "ui.subtitle": "Weltbuch & Spielerkodex",
  "ui.tagline": "Alles, was du über diese Welt, ihre Götter, Völker, Helden und die harten Gesetze des Überlebens wissen musst.",
  "ui.people": "Gestalten der Chronik",
  "ui.quote": "„Der Große Hirsch sang diese Welt ins Dasein — nun wird ihr Schicksal mit Stahl, Gold und Bündnissen besungen.“",
  "lore.I.t": "Das kosmische Lied",
  "lore.I.s": "Handgai und die Geburt der Welt",
  "lore.I.x": "Vor allen Dingen gab es ein endloses Meer. Handgai, der Große Hirsch, formte Dengin, hob den Himmel empor und führte das Leben von den kleinsten Meereswesen bis zu den Menschen der Steppe. Das Universum wurde ins Dasein gesungen, und jeder Stein, jedes Tier und jeder Mensch bleibt Teil dieser göttlichen Melodie.",
  "lore.II.t": "Das Gesetz der Widrigkeit",
  "lore.II.s": "Leiden ist das Feuer, das härtet",
  "lore.II.x": "Bequemlichkeit ist eine Falle. Fortschritt entsteht aus Entbehrung, Hunger und der Beherrschung der Natur. Leiden gilt als ein buchstäbliches Feuer, das menschliche Stärke härtet, während ein Leben ohne Mühsal weiche und erstarrte Gesellschaften hervorbringt.",
  "lore.III.t": "Das Tierpantheon",
  "lore.III.s": "Götter in den Gestalten heiliger Tiere",
  "lore.III.x": "Die Götter wandeln in Tiergestalt durch die Welt. Der Adler ist das göttliche Gewissen, der Bär steht für Stärke und Zügelung, die Eule ist ein absolutes Tabu, der Fuchs warnt vor Unheil, und die Ratte verkörpert Krankheit und Verrat. Handgai, der Große Hirsch, ist der höchste Schöpfer.",
  "lore.IV.t": "Die große Teilung",
  "lore.IV.s": "Die Steppe und das Steinreich",
  "lore.IV.x": "Die Welt wird vom Großen Fluss geteilt. Im Norden ziehen bewegliche Clans mit ihren Herden und Werkstätten in gewaltigen, kunstvoll konstruierten Jurten umher. Im Süden stützt sich ein bürokratisches Reich auf Stein, Gesetz, Papier, Berufsheere und gewaltige Befestigungen.",
  "lore.V.t": "Regeln des Überlebens",
  "lore.V.s": "Steppengesetze und besondere Rollen",
  "lore.V.x": "Die Jagd muss nachhaltig bleiben, Kleidung wird mit Tierfett gegen die Kälte versiegelt, und Nahrung wird innerhalb des Clans geteilt. Verbannung ist die äußerste Strafe. Kundschafter sind geachtete Eliten, während Schamanen als Ärzte, Traumdeuter und politische Berater dienen.",
  "lore.VI.t": "Die Mächte der Grenzlande",
  "lore.VI.s": "Ganbataar, Bolormaa und Temüü",
  "lore.VI.x": "Ganbataar herrscht durch Angst und Kollektivstrafen. Bolormaa bringt Bildung, Diplomatie und neue Technik aus fernen Ländern. Temüü, der feinfühlige Erbe, sucht eine Meritokratie, die auf gemeinsamen Interessen statt auf Grausamkeit beruht.",
  "lore.VII.t": "Die Zeitalter",
  "lore.VII.s": "Die Welt vor dem Krieg",
  "lore.VII.x": "Die Menschheit begann unter dem kosmischen Lied und vergaß es dann. Der Süden wandte sich Landwirtschaft und Bürokratie zu, während der Norden Ausdauer aus Kälte und Knappheit lernte. Später schmiedete Ganbataar die verstreuten Clans zu einer disziplinierten Militärmacht.",
  "lore.VIII.t": "Strategische Lande",
  "lore.VIII.s": "Die Karte als Waffe",
  "lore.VIII.x": "Flussübergänge, hohe Gebirgspässe und Feuchtgebiete sind entscheidende strategische Güter. Brücken sichern Handel und Raubzüge, Bergpässe halten südliche Heere auf, und fruchtbare Sümpfe bleiben umkämpftes Land, auf dem rivalisierende Clans einander jagen und aus dem Hinterhalt angreifen.",
  "lore.IX.t": "Der Hinterhalt",
  "lore.IX.s": "Die Waldfalle und die Lehre der Belagerung",
  "lore.IX.x": "Batu lockte ein südliches Heer in einen vorgetäuschten Rückzug und traf dann seine Flanke mit Brandpfeilen. Kundschafter sabotierten die Festung von innen, während Ingenieure die äußere Mauer niederrissen. Die Lehre war klar: Leichte Reiterei beherrscht offenes Gelände, doch eine lange Belagerung verlangt Disziplin und die richtigen Maschinen.",
  "lore.X.t": "Der Wolf",
  "lore.X.s": "Der Zähmer von Dunkelheit und Gleichgewicht",
  "lore.X.x": "Ein dunkler kosmischer Besucher wählte die Gestalt eines Wolfes. Obwohl seine äußere Energie Zerstörung brachte, war sein Kern reines Licht. Der Wolf wurde zum Zeichen des Gleichgewichts: Es gibt kein Licht ohne Dunkelheit, und die Liebe beginnt das Werk, das das Gleichgewicht bewahrt.",
  "lore.XI.t": "Zeremonie und Heldentum",
  "lore.XI.s": "Kehlgesang, Bestattung und Temüüs Schwur",
  "lore.XI.x": "Nach der Schlacht beruhigten Schamanen die Geister, reinigten das Feld und bestatteten die Toten. Mit Kehlgesang spendeten sie Heilern und Sterbenden Trost. Danach drängte Qorchi den jungen Temüü zu einem öffentlichen Zweikampf mit seinem tyrannischen Vater und setzte ihn auf den Pfad, die Clans zu einen.",
  "lore.XII.t": "Ein Familienzwist",
  "lore.XII.s": "Das Duell und der Aufstieg der Macht",
  "lore.XII.x": "Temüü forderte Ganbataar heraus und besiegte ihn in einem brutalen Zweikampf. Dann wandte er sich nach Westen, entmachtete die alten Kriegsherren und stellte Verdienst über Blut und Rache. Zwischen Osten und Westen ließ er die erste Verwaltungsstadt errichten.",
  "lore.XIII.t": "Die Machtübertragung",
  "lore.XIII.s": "Einigungskriege und eine neue Taktik",
  "lore.XIII.x": "Temüü einte die Clans durch Disziplin, Schildwälle, berittene Bogenschützen, Belagerungsmaschinen und einen entscheidenden Schlag gegen das feindliche Zentrum. Auf Raubzüge folgten Eroberung, Gesetz, Handel und eine einzige Zentralverwaltung.",
  "lore.XIV.t": "Der Wiederaufbau",
  "lore.XIV.s": "Ulanbataar und die Bedrohung aus dem Süden",
  "lore.XIV.x": "Die neue Hauptstadt erhob sich in Ulanbataar. Temüü belohnte Soldaten und Bauern, ließ den ehrgeizigen Schamanen Qorchi einsperren und verbot Gewalt gegen Frauen und Kinder. Dann traf ein Gesandter aus dem Süden ein, mit einer Drohung im Rücken, die von einem Millionenheer gestützt wurde.",
  "lore.XV.t": "Neues Leben, alte Gewohnheiten",
  "lore.XV.s": "Der Feldzug gegen das südliche Heer",
  "lore.XV.x": "Temüü versprach, an vorderster Front zu führen, doch der Feldzug brachte Hinterhalte, Sabotage und einen Fluss, der von aneinandergeketteten Schiffen versperrt war. Das Steppenheer verfügte über Geschwindigkeit und Disziplin; das südliche Reich über Zahl, Feuerwaffen und befestigte Stellungen.",
  "lore.XVI.t": "Der endlose Krieg",
  "lore.XVI.s": "Brücken, der Fluss und der Stillstand",
  "lore.XVI.x": "Ingenieure errichteten unter Beschuss Brücken, und Reiterei nutzte vorgetäuschte Rückzüge, um die südliche Linie zu brechen. Doch die Küstenmauern ließen sich nicht nehmen. Die letzte Lehre lautete, militärische Stärke mit autonomer Verwaltung, Handel und Achtung vor südlichem Wissen zu verbinden.",
  "lore.XVII.t": "Jede Nacht endet im Morgengrauen",
  "lore.XVII.s": "Frieden, Heimkehr und eine Dynastie",
  "lore.XVII.x": "Vom Krieg erschöpft kehrte Temüü nach Ulanbataar zurück und wählte den Frieden. Er wollte, dass die Bevölkerung wuchs, die Heere jüngeren Offizieren anvertraut wurden und das Reich durch Einheit statt durch endlose Eroberung stark wurde.",
  "lore.XVIII.t": "Nachwort",
  "lore.XVIII.s": "Die Geschichten, die uns binden",
  "lore.XVIII.x": "Keine Armee ist unbesiegbar, und keine Dynastie währt ewig. Menschen sind stammesgebunden und gewaltsam, aber auch sozial, politisch, einfühlsam und fähig, über sich hinauszuwachsen. Was uns bindet, sind nicht Sieg oder Niederlage, sondern die Geschichten, die wir teilen.",
  "rule.0.t": "Nachhaltige Jagd",
  "rule.0.x": "Nimm von der Natur, ohne sie zu zerstören, sonst wird Handgai sich abwenden.",
  "rule.1.t": "Schutz durch Tierfett",
  "rule.1.x": "Kleidung und Rüstungen werden gegen tödliche Kälte, Wind und Nässe versiegelt.",
  "rule.2.t": "Radikale Gleichheit",
  "rule.2.x": "Nahrung und Ressourcen werden innerhalb des Clans geteilt; Horten führt zur Verbannung.",
  "rule.3.t": "Die Drohung der Verbannung",
  "rule.3.x": "Wer Stammesrecht bricht, ist dem sicheren Tod in einer Wildnis ausgeliefert, in der Überleben Zusammenarbeit verlangt.",
  "rule.4.t": "Kundschaftergilden",
  "rule.4.x": "Kundschafter sind elitäre Kartographen und Hüter verborgener Handelsrouten.",
  "rule.5.t": "Schamanen",
  "rule.5.x": "Schamanen deuten Geister, heilen Kranke, lesen Träume und beraten Herrscher.",
  "pan.0.n": "Handgai, der Große Hirsch",
  "pan.0.x": "Der höchste Schöpfer, der das Leben lenkt und fürchtet, was die Menschheit zerstören könnte.",
  "pan.1.n": "Der Adler",
  "pan.1.x": "Die Augen des Himmels und das göttliche Gewissen.",
  "pan.2.n": "Der Bär",
  "pan.2.x": "Rohe Stärke, im Gleichgewicht gehalten durch absolute Selbstbeherrschung.",
  "pan.3.n": "Die Eule",
  "pan.3.x": "Ein absolutes Tabu; ihr Schaden zuzufügen ist ein geistliches Verbrechen.",
  "pan.4.n": "Der Fuchs",
  "pan.4.x": "Ein Vorzeichen des Unheils vor einer Reise oder Schlacht.",
  "pan.5.n": "Die Ratte",
  "pan.5.x": "Krankheit, Fäulnis und Verrat, denen sich alle Clans einmal im Jahr widersetzen.",
  "char.0.n": "Temüü",
  "char.0.r": "Der Einiger",
  "char.0.x": "Ein feinfühliger und kluger Junge, der seinen tyrannischen Vater besiegt, die Clans eint und die Spannung zwischen Mitgefühl und Gewalt in sich trägt.",
  "char.1.n": "Ganbataar",
  "char.1.r": "Der Tyrann",
  "char.1.x": "Ein trunksüchtiger, gewalttätiger Kriegsherr, der seine Familie durch Angst beherrscht und im Zweikampf mit Temüü stirbt.",
  "char.2.n": "Qorchi",
  "char.2.r": "Der Schamane",
  "char.2.x": "Ein Deuter kosmischer Kräfte, der Temüü zur Macht führt und dabei still seine eigene Einflussmacht ausbaut.",
  "char.3.n": "Bolormaa",
  "char.3.r": "Die Reformerin",
  "char.3.x": "Eine Bringerin von Schrift, Bildung, Diplomatie und Schutz für Frauen und Kinder.",
  "char.4.n": "Batu",
  "char.4.r": "Der Feldherr",
  "char.4.x": "Ein Feldkommandeur, dessen vorgetäuschter Rückzug und Hinterhalt mit Brandpfeilen legendär werden.",
  "char.5.n": "Der Himmlische Kaiser",
  "char.5.r": "Der südliche Herrscher",
  "char.5.x": "Ein stolzer Herrscher mit einem gewaltigen Heer und uneinnehmbaren Mauern, der auf offenem Feld besiegt wird."
};

export default translations;
