// Kronikan (Codex) käännös (es). Avaimet vastaavat Codex.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.back": "Volver al juego",
  "ui.rulebook": "Libro de reglas",
  "ui.eyebrow": "Cuentos de la Estepa",
  "ui.title": "La Crónica de las Fronteras",
  "ui.subtitle": "Libro del mundo & códice del jugador",
  "ui.tagline": "Aquí encontrarás todo lo que necesitas saber sobre el mundo, sus dioses, pueblos, héroes y las duras leyes de la supervivencia.",
  "ui.people": "Personajes de la crónica",
  "ui.quote": "“El Gran Ciervo cantó este mundo hasta darle existencia — ahora su destino se canta con acero, oro y alianzas.”",
  "lore.I.t": "El Canto Cósmico",
  "lore.I.s": "Handgai y el nacimiento del mundo",
  "lore.I.x": "Antes de todas las cosas existía un mar infinito. Handgai, el Gran Ciervo, dio forma a Dengin, alzó el cielo y guio la vida desde los más pequeños organismos marinos hasta los pueblos de la estepa. El universo fue cantado hasta existir, y cada piedra, animal y persona sigue formando parte de esa melodía divina.",
  "lore.II.t": "La Ley de la Adversidad",
  "lore.II.s": "El sufrimiento es el fuego que templa",
  "lore.II.x": "La comodidad es una trampa. El progreso nace de la dureza, del hambre y del dominio de la naturaleza. El sufrimiento se entiende como un fuego literal que endurece la fuerza humana, mientras que una vida sin dificultad produce sociedades blandas y estancadas.",
  "lore.III.t": "El Panteón Animal",
  "lore.III.s": "Dioses con la forma de animales sagrados",
  "lore.III.x": "Los dioses caminan por el mundo con forma animal. El Águila es la conciencia divina, el Oso es la fuerza y la contención, el Búho es un tabú absoluto, el Zorro advierte del desastre y la Rata representa la enfermedad y la traición. Handgai, el Gran Ciervo, es el creador supremo.",
  "lore.IV.t": "La Gran División",
  "lore.IV.s": "La estepa y el imperio de piedra",
  "lore.IV.x": "El mundo está dividido por el Gran Río. En el norte, clanes móviles viajan con sus rebaños y talleres en vastas yurtas diseñadas con pericia. En el sur, un imperio burocrático depende de la piedra, la ley, el papel, ejércitos profesionales e inmensas fortificaciones.",
  "lore.V.t": "Reglas de supervivencia",
  "lore.V.s": "Leyes de la estepa y funciones especiales",
  "lore.V.x": "La caza debe seguir siendo sostenible, la ropa se sella contra el frío con grasa animal y la comida se comparte dentro del clan. El exilio es el castigo definitivo. Los exploradores son una élite respetada, mientras que los chamanes sirven como médicos, intérpretes de sueños y consejeros políticos.",
  "lore.VI.t": "Los poderes de las Fronteras",
  "lore.VI.s": "Ganbataar, Bolormaa y Temüü",
  "lore.VI.x": "Ganbataar gobierna mediante el miedo y el castigo colectivo. Bolormaa trae saber, diplomacia y nueva tecnología desde tierras lejanas. Temüü, el heredero sensible, busca una meritocracia construida sobre intereses compartidos en lugar de la crueldad.",
  "lore.VII.t": "Las Eras",
  "lore.VII.s": "El mundo antes de la guerra",
  "lore.VII.x": "La humanidad comenzó bajo el Canto Cósmico y luego lo olvidó. El sur abrazó la agricultura y la burocracia, mientras el norte aprendió la resistencia del frío y la escasez. Más tarde, Ganbataar forjó a los clanes dispersos hasta convertirlos en una potencia militar disciplinada.",
  "lore.VIII.t": "Tierras estratégicas",
  "lore.VIII.s": "El mapa como arma",
  "lore.VIII.x": "Los cruces de río, los altos pasos de montaña y las tierras húmedas son recursos estratégicos decisivos. Los puentes aseguran el comercio y las incursiones, los pasos montañosos detienen a los ejércitos del sur, y los fértiles humedales siguen siendo un terreno disputado donde clanes rivales cazan y se emboscan unos a otros.",
  "lore.IX.t": "Emboscada",
  "lore.IX.s": "La trampa del bosque y la lección del asedio",
  "lore.IX.x": "Batu atrajo a un ejército del sur con una falsa retirada y luego golpeó su flanco con flechas incendiarias. Los exploradores sabotearon la fortaleza desde dentro, mientras los ingenieros derribaban la muralla exterior. La lección fue clara: la caballería ligera domina el terreno abierto, pero un asedio prolongado exige disciplina y máquinas adecuadas.",
  "lore.X.t": "El Lobo",
  "lore.X.s": "El domador de la oscuridad y el equilibrio",
  "lore.X.x": "Un oscuro visitante cósmico eligió la forma de un lobo. Aunque su energía exterior traía destrucción, en su núcleo había luz pura. El lobo se convirtió en signo de equilibrio: no hay luz sin oscuridad, y el amor inicia la obra que el equilibrio sostiene.",
  "lore.XI.t": "Ceremonia y heroísmo",
  "lore.XI.s": "Canto gutural, entierro y el juramento de Temüü",
  "lore.XI.x": "Tras la batalla, los chamanes calmaban a los espíritus, purificaban el campo y enterraban a los muertos. Mediante el canto gutural consolaban a los sanadores y a los moribundos. Qorchi empujó entonces al joven Temüü hacia un duelo público con su padre tirano, poniéndolo en el camino de unir a los clanes.",
  "lore.XII.t": "Una disputa familiar",
  "lore.XII.s": "El duelo y el ascenso del poder",
  "lore.XII.x": "Temüü desafió a Ganbataar y lo derrotó en un brutal duelo. Después se volvió hacia el oeste, apartó a los viejos caudillos de guerra y eligió el mérito por encima de la sangre y la venganza. Se ordenó construir la primera ciudad administrativa entre oriente y occidente.",
  "lore.XIII.t": "La transferencia del poder",
  "lore.XIII.s": "Guerras de unificación y una nueva táctica",
  "lore.XIII.x": "Temüü unió a los clanes mediante disciplina, muros de escudos, arqueros montados, máquinas de asedio y un golpe decisivo contra el centro enemigo. Las incursiones cedieron su lugar a la conquista, la ley, el comercio y una sola administración central.",
  "lore.XIV.t": "Reconstrucción",
  "lore.XIV.s": "Ulanbataar y la amenaza del sur",
  "lore.XIV.x": "La nueva capital se alzó en Ulanbataar. Temüü recompensó a soldados y campesinos, encarceló al ambicioso chamán Qorchi y proscribió la violencia contra mujeres y niños. Luego llegó un enviado del sur con una amenaza respaldada por un ejército de un millón de hombres.",
  "lore.XV.t": "Nueva vida, viejos hábitos",
  "lore.XV.s": "La marcha contra el ejército del sur",
  "lore.XV.x": "Temüü prometió liderar desde el frente, pero la marcha trajo emboscadas, sabotaje y un río bloqueado por barcos encadenados. El ejército de la estepa tenía velocidad y disciplina; el imperio del sur tenía número, armas de fuego y posiciones fortificadas.",
  "lore.XVI.t": "La guerra interminable",
  "lore.XVI.s": "Puentes, el río y el punto muerto",
  "lore.XVI.x": "Los ingenieros levantaron puentes bajo fuego, y la caballería usó retiradas fingidas para quebrar la línea del sur. Sin embargo, las murallas costeras no pudieron tomarse. La lección final fue combinar la fuerza militar con una administración autónoma, el comercio y el respeto por el saber del sur.",
  "lore.XVII.t": "Toda noche termina en alba",
  "lore.XVII.s": "Paz, retorno y una dinastía",
  "lore.XVII.x": "Exhausto por la guerra, Temüü regresó a Ulanbataar y eligió la paz. Quería que la población creciera, que los ejércitos se confiaran a oficiales más jóvenes y que el imperio se hiciera fuerte mediante la unidad en vez de la conquista interminable.",
  "lore.XVIII.t": "Epílogo",
  "lore.XVIII.s": "Las historias que nos unen",
  "lore.XVIII.x": "Ningún ejército es invencible y ninguna dinastía dura para siempre. Las personas son tribales y violentas, pero también sociales, políticas, empáticas y capaces de superarse. Lo que nos une no es la victoria ni la derrota, sino las historias que compartimos.",
  "rule.0.t": "Caza sostenible",
  "rule.0.x": "Toma de la naturaleza sin destruirla, o Handgai te dará la espalda.",
  "rule.1.t": "Protección con grasa animal",
  "rule.1.x": "La ropa y la armadura se sellan contra el frío letal, el viento y la humedad.",
  "rule.2.t": "Igualdad radical",
  "rule.2.x": "La comida y los recursos se comparten dentro del clan; el acaparamiento conduce al exilio.",
  "rule.3.t": "La amenaza del exilio",
  "rule.3.x": "Romper la ley tribal significa una muerte segura en una tierra salvaje donde sobrevivir exige cooperación.",
  "rule.4.t": "Gremios de exploradores",
  "rule.4.x": "Los exploradores son cartógrafos de élite y guardianes de rutas comerciales ocultas.",
  "rule.5.t": "Chamanes",
  "rule.5.x": "Los chamanes interpretan a los espíritus, curan a los enfermos, leen los sueños y aconsejan a los gobernantes.",
  "pan.0.n": "Handgai, el Gran Ciervo",
  "pan.0.x": "El creador supremo, que guía la vida y teme aquello que la humanidad pueda destruir.",
  "pan.1.n": "El Águila",
  "pan.1.x": "Los ojos del cielo y la conciencia divina.",
  "pan.2.n": "El Oso",
  "pan.2.x": "Fuerza bruta equilibrada por una contención absoluta.",
  "pan.3.n": "El Búho",
  "pan.3.x": "Un tabú absoluto; dañar a uno es un crimen espiritual.",
  "pan.4.n": "El Zorro",
  "pan.4.x": "Un augurio de desastre antes de un viaje o una batalla.",
  "pan.5.n": "La Rata",
  "pan.5.x": "Enfermedad, podredumbre y traición, combatidas por todos los clanes una vez al año.",
  "char.0.n": "Temüü",
  "char.0.r": "El unificador",
  "char.0.x": "Un muchacho sensible e inteligente que derrota a su padre tirano, une a los clanes y lleva dentro la tensión entre la empatía y la violencia.",
  "char.1.n": "Ganbataar",
  "char.1.r": "El tirano",
  "char.1.x": "Un señor de la guerra ebrio y violento que gobierna a su familia mediante el miedo y muere en un duelo con Temüü.",
  "char.2.n": "Qorchi",
  "char.2.r": "El chamán",
  "char.2.x": "Intérprete de las fuerzas cósmicas que guía a Temüü hacia el poder mientras, en silencio, construye su propia influencia.",
  "char.3.n": "Bolormaa",
  "char.3.r": "La reformadora",
  "char.3.x": "Portadora de la escritura, el saber, la diplomacia y la protección de mujeres y niños.",
  "char.4.n": "Batu",
  "char.4.r": "El comandante",
  "char.4.x": "Un comandante de campaña cuya falsa retirada y emboscada de flechas incendiarias se vuelven legendarias.",
  "char.5.n": "El Emperador Celestial",
  "char.5.r": "El gobernante del sur",
  "char.5.x": "Un gobernante orgulloso con un ejército inmenso y murallas inexpugnables, derrotado en campo abierto."
};

export default translations;
