// Kronikan (Codex) käännös (fr). Avaimet vastaavat Codex.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.back": "Retour au jeu",
  "ui.rulebook": "Livre des règles",
  "ui.eyebrow": "Contes de la Steppe",
  "ui.title": "La Chronique des confins",
  "ui.subtitle": "Livre du monde & Codex du joueur",
  "ui.tagline": "Tout ce qu’il faut savoir sur le monde, ses dieux, ses peuples, ses héros et les dures lois de la survie.",
  "ui.people": "Personnages de la Chronique",
  "ui.quote": "« Le Grand Cerf a chanté ce monde à l’existence — et désormais son destin se chante avec l’acier, l’or et les alliances. »",
  "lore.I.t": "Le Chant cosmique",
  "lore.I.s": "Handgai et la naissance du monde",
  "lore.I.x": "Avant toute chose, il y avait une mer sans fin. Handgai, le Grand Cerf, façonna Dengin, éleva le ciel et guida la vie, depuis les plus infimes organismes marins jusqu’aux peuples de la steppe. L’univers fut chanté à l’existence, et chaque pierre, chaque animal et chaque personne demeure une part de cette mélodie divine.",
  "lore.II.t": "La Loi de l’adversité",
  "lore.II.s": "La souffrance est le feu qui trempe",
  "lore.II.x": "Le confort est un piège. Le progrès naît de l’épreuve, de la faim et de la maîtrise de la nature. La souffrance est tenue pour un feu bien réel qui endurcit la force humaine, tandis qu’une vie sans difficulté engendre des sociétés molles et stagnantes.",
  "lore.III.t": "Le Panthéon animal",
  "lore.III.s": "Des dieux sous l’apparence d’animaux sacrés",
  "lore.III.x": "Les dieux parcourent le monde sous forme animale. L’Aigle est la conscience divine, l’Ours la force et la retenue, la Chouette un tabou absolu, le Renard un avertissement de désastre, et le Rat représente la maladie et la trahison. Handgai, le Grand Cerf, est le créateur suprême.",
  "lore.IV.t": "La Grande Séparation",
  "lore.IV.s": "La steppe et l’empire de pierre",
  "lore.IV.x": "Le monde est scindé par le Grand Fleuve. Au nord, des clans mobiles voyagent avec leurs troupeaux et leurs ateliers dans de vastes yourtes d’ingénierie savante. Au sud, un empire bureaucratique s’appuie sur la pierre, la loi, le papier, des armées professionnelles et d’immenses fortifications.",
  "lore.V.t": "Les lois de la survie",
  "lore.V.s": "Lois de la steppe et rôles particuliers",
  "lore.V.x": "La chasse doit rester durable, les vêtements sont scellés contre le froid par la graisse animale, et la nourriture se partage au sein du clan. L’exil est le châtiment suprême. Les éclaireurs sont une élite respectée, tandis que les chamans servent de médecins, d’interprètes des rêves et de conseillers politiques.",
  "lore.VI.t": "Les puissances des confins",
  "lore.VI.s": "Ganbataar, Bolormaa et Temüü",
  "lore.VI.x": "Ganbataar règne par la peur et le châtiment collectif. Bolormaa apporte l’écriture, le savoir, la diplomatie et de nouvelles techniques venues de terres lointaines. Temüü, héritier sensible, cherche une méritocratie fondée sur les intérêts partagés plutôt que sur la cruauté.",
  "lore.VII.t": "Les Âges",
  "lore.VII.s": "Le monde avant la guerre",
  "lore.VII.x": "L’humanité naquit sous le Chant cosmique, puis l’oublia. Le sud embrassa l’agriculture et la bureaucratie, tandis que le nord apprit l’endurance au froid et à la rareté. Plus tard, Ganbataar forgea les clans dispersés en une puissance militaire disciplinée.",
  "lore.VIII.t": "Terres stratégiques",
  "lore.VIII.s": "La carte comme arme",
  "lore.VIII.x": "Les gués du fleuve, les hauts cols de montagne et les zones humides sont des atouts stratégiques décisifs. Les ponts assurent le commerce et les raids, les cols arrêtent les armées du sud, et les marais fertiles demeurent des terres disputées où des clans rivaux chassent et se tendent des embuscades.",
  "lore.IX.t": "Embuscade",
  "lore.IX.s": "Le piège de la forêt et la leçon du siège",
  "lore.IX.x": "Batu attira une armée méridionale dans une fausse retraite, puis frappa son flanc avec des flèches enflammées. Les éclaireurs sabotèrent la forteresse de l’intérieur, tandis que les ingénieurs abattaient le mur extérieur. La leçon était claire : la cavalerie légère domine le terrain découvert, mais un long siège exige de la discipline et de bonnes machines.",
  "lore.X.t": "Le Loup",
  "lore.X.s": "Le dompteur des ténèbres et de l’équilibre",
  "lore.X.x": "Un sombre visiteur cosmique choisit la forme d’un loup. Si son énergie apparente apportait la destruction, son cœur était de pure lumière. Le loup devint le signe de l’équilibre : il n’est pas de lumière sans ténèbres, et l’amour entreprend l’œuvre que l’équilibre soutient.",
  "lore.XI.t": "Cérémonie et héroïsme",
  "lore.XI.s": "Chant diphonique, sépulture et vœu de Temüü",
  "lore.XI.x": "Après la bataille, les chamans apaisèrent les esprits, purifièrent le champ et enterrèrent les morts. Par le chant diphonique, ils réconfortaient les guérisseurs et les mourants. Qorchi poussa alors le jeune Temüü vers un duel public contre son père tyrannique, le mettant sur la voie de l’union des clans.",
  "lore.XII.t": "Une querelle de famille",
  "lore.XII.s": "Le duel et l’ascension du pouvoir",
  "lore.XII.x": "Temüü défia Ganbataar et le vainquit dans un duel brutal. Puis il se tourna vers l’ouest, écarta les anciens chefs de guerre et choisit le mérite plutôt que le sang et la vengeance. Il ordonna la construction de la première cité administrative entre l’est et l’ouest.",
  "lore.XIII.t": "Le transfert du pouvoir",
  "lore.XIII.s": "Guerres d’unification et nouvelle tactique",
  "lore.XIII.x": "Temüü unifia les clans par la discipline, les murs de boucliers, les archers montés, les machines de siège et une frappe décisive au centre ennemi. Les raids cédèrent la place à la conquête, à la loi, au commerce et à une administration centrale unique.",
  "lore.XIV.t": "Reconstruction",
  "lore.XIV.s": "Ulanbataar et la menace du sud",
  "lore.XIV.x": "La nouvelle capitale s’éleva à Ulanbataar. Temüü récompensa soldats et paysans, fit emprisonner le chaman ambitieux Qorchi et proscrivit la violence envers les femmes et les enfants. Puis arriva un émissaire du sud porteur d’une menace appuyée par une armée d’un million d’hommes.",
  "lore.XV.t": "Une vie nouvelle, de vieilles habitudes",
  "lore.XV.s": "La marche contre l’armée du sud",
  "lore.XV.x": "Temüü promit de mener depuis l’avant, mais la marche apporta embuscades, sabotages et un fleuve barré par des navires enchaînés. L’armée de la steppe avait la vitesse et la discipline ; l’empire du sud avait le nombre, les armes à feu et des positions fortifiées.",
  "lore.XVI.t": "La guerre sans fin",
  "lore.XVI.s": "Ponts, fleuve et impasse",
  "lore.XVI.x": "Les ingénieurs bâtirent des ponts sous le feu et la cavalerie usa de fausses retraites pour briser la ligne méridionale. Pourtant, les murailles côtières ne purent être prises. La leçon finale fut d’unir la force militaire à une administration autonome, au commerce et au respect du savoir du sud.",
  "lore.XVII.t": "Toute nuit s’achève à l’aube",
  "lore.XVII.s": "Paix, retour et dynastie",
  "lore.XVII.x": "Épuisé par la guerre, Temüü revint à Ulanbataar et choisit la paix. Il voulait voir croître la population, confier les armées à de plus jeunes officiers et rendre l’empire fort par l’unité plutôt que par une conquête sans fin.",
  "lore.XVIII.t": "Postface",
  "lore.XVIII.s": "Les histoires qui nous lient",
  "lore.XVIII.x": "Nulle armée n’est invincible et nulle dynastie ne dure à jamais. Les êtres humains sont tribaux et violents, mais aussi sociaux, politiques, empathiques et capables de se dépasser. Ce qui nous lie n’est ni la victoire ni la défaite, mais les histoires que nous partageons.",
  "rule.0.t": "Chasse durable",
  "rule.0.x": "Prends à la nature sans la détruire, ou Handgai détournera son regard.",
  "rule.1.t": "Protection à la graisse animale",
  "rule.1.x": "Les vêtements et les armures sont scellés contre le froid meurtrier, le vent et l’humidité.",
  "rule.2.t": "Égalité radicale",
  "rule.2.x": "La nourriture et les ressources se partagent au sein du clan ; thésauriser mène à l’exil.",
  "rule.3.t": "La menace de l’exil",
  "rule.3.x": "Briser la loi tribale, c’est une mort certaine dans une sauvagerie où la survie exige la coopération.",
  "rule.4.t": "Guildes d’éclaireurs",
  "rule.4.x": "Les éclaireurs sont une élite de cartographes et les gardiens de routes commerciales secrètes.",
  "rule.5.t": "Chamans",
  "rule.5.x": "Les chamans interprètent les esprits, soignent les malades, lisent les rêves et conseillent les souverains.",
  "pan.0.n": "Handgai, le Grand Cerf",
  "pan.0.x": "Le créateur suprême, qui guide la vie et redoute ce que l’humanité pourrait détruire.",
  "pan.1.n": "L’Aigle",
  "pan.1.x": "Les yeux du ciel et la conscience divine.",
  "pan.2.n": "L’Ours",
  "pan.2.x": "Une force brute équilibrée par une retenue absolue.",
  "pan.3.n": "La Chouette",
  "pan.3.x": "Un tabou absolu ; en blesser une est un crime spirituel.",
  "pan.4.n": "Le Renard",
  "pan.4.x": "Un présage de désastre avant un voyage ou une bataille.",
  "pan.5.n": "Le Rat",
  "pan.5.x": "La maladie, la pourriture et la trahison, combattues une fois l’an par chaque clan.",
  "char.0.n": "Temüü",
  "char.0.r": "L’unificateur",
  "char.0.x": "Un garçon sensible et intelligent qui vainc son père tyrannique, unit les clans et porte en lui la tension entre l’empathie et la violence.",
  "char.1.n": "Ganbataar",
  "char.1.r": "Le tyran",
  "char.1.x": "Un seigneur de guerre ivrogne et violent qui gouverne sa famille par la peur et meurt dans un duel contre Temüü.",
  "char.2.n": "Qorchi",
  "char.2.r": "Le chaman",
  "char.2.x": "Interprète des forces cosmiques, il guide Temüü vers le pouvoir tout en bâtissant discrètement sa propre influence.",
  "char.3.n": "Bolormaa",
  "char.3.r": "La réformatrice",
  "char.3.x": "Porteuse de l’écriture, du savoir, de la diplomatie et des protections accordées aux femmes et aux enfants.",
  "char.4.n": "Batu",
  "char.4.r": "Le commandant",
  "char.4.x": "Un commandant de terrain dont la fausse retraite et l’embuscade aux flèches enflammées deviennent légendaires.",
  "char.5.n": "L’Empereur céleste",
  "char.5.r": "Le souverain du sud",
  "char.5.x": "Un souverain orgueilleux à l’armée immense et aux murailles imprenables, vaincu en terrain découvert."
};

export default translations;
