// Kronikan (Codex) käännös (id). Avaimet vastaavat Codex.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.back": "Kembali ke permainan",
  "ui.rulebook": "Buku Aturan",
  "ui.eyebrow": "Kisah-Kisah Padang Stepa",
  "ui.title": "Kronik Perbatasan",
  "ui.subtitle": "Kitab Dunia & Kodeks Pemain",
  "ui.tagline": "Segala yang perlu diketahui tentang dunia ini, para dewa, bangsa-bangsa, pahlawan, dan hukum-hukum keras untuk bertahan hidup.",
  "ui.people": "Tokoh-Tokoh Kronik",
  "ui.quote": "“Dunia ini dinyanyikan menjadi ada oleh Sang Rusa Agung — kini nasibnya dinyanyikan dengan baja, emas, dan persekutuan.”",
  "lore.I.t": "Nyanyian Kosmik",
  "lore.I.s": "Handgai dan kelahiran dunia",
  "lore.I.x": "Sebelum segala sesuatu, yang ada hanyalah lautan tanpa tepi. Handgai, Sang Rusa Agung, membentuk Dengin, mengangkat langit, dan menuntun kehidupan dari organisme laut yang paling kecil hingga menjadi manusia-manusia padang stepa. Alam semesta dinyanyikan menjadi ada, dan setiap batu, hewan, dan insan tetap menjadi bagian dari melodi ilahi itu.",
  "lore.II.t": "Hukum Kesengsaraan",
  "lore.II.s": "Penderitaan adalah api yang menempa",
  "lore.II.x": "Kenyamanan adalah jebakan. Kemajuan lahir dari kesukaran, kelaparan, dan penguasaan atas alam. Penderitaan dipandang sebagai api yang sungguh-sungguh mengeraskan kekuatan manusia, sementara hidup tanpa kesulitan melahirkan masyarakat yang lunak dan mandek.",
  "lore.III.t": "Panteon Hewan",
  "lore.III.s": "Para dewa dalam rupa hewan-hewan suci",
  "lore.III.x": "Para dewa menjelajahi dunia dalam wujud hewan. Elang adalah hati nurani ilahi, Beruang adalah kekuatan dan pengendalian diri, Burung Hantu adalah pantangan mutlak, Rubah memperingatkan bencana, dan Tikus melambangkan penyakit serta pengkhianatan. Handgai, Sang Rusa Agung, adalah pencipta tertinggi.",
  "lore.IV.t": "Perpecahan Besar",
  "lore.IV.s": "Padang stepa dan kekaisaran batu",
  "lore.IV.x": "Dunia terbelah oleh Sungai Besar. Di utara, klan-klan yang bergerak hidup berpindah bersama kawanan dan bengkel mereka di dalam yurt raksasa yang direkayasa dengan cermat. Di selatan, sebuah kekaisaran birokratis bertumpu pada batu, hukum, kertas, tentara profesional, dan benteng-benteng yang sangat besar.",
  "lore.V.t": "Aturan Bertahan Hidup",
  "lore.V.s": "Hukum padang stepa dan peran-peran khusus",
  "lore.V.x": "Perburuan harus tetap lestari, pakaian disegel dari dingin dengan lemak hewan, dan makanan dibagi di dalam klan. Pengasingan adalah hukuman yang paling berat. Para pengintai adalah kalangan elite yang dihormati, sedangkan syaman menjadi tabib, penafsir mimpi, dan penasihat politik.",
  "lore.VI.t": "Kekuatan-Kekuatan Perbatasan",
  "lore.VI.s": "Ganbataar, Bolormaa, dan Temüü",
  "lore.VI.x": "Ganbataar memerintah melalui ketakutan dan hukuman kolektif. Bolormaa membawa ilmu, diplomasi, dan teknologi baru dari negeri-negeri jauh. Temüü, sang pewaris yang peka, mendambakan meritokrasi yang dibangun di atas kepentingan bersama, bukan kekejaman.",
  "lore.VII.t": "Zaman-Zaman",
  "lore.VII.s": "Dunia sebelum perang",
  "lore.VII.x": "Umat manusia bermula di bawah Nyanyian Kosmik, lalu melupakannya. Selatan memilih pertanian dan birokrasi, sedangkan utara belajar ketahanan dari dingin dan kekurangan. Belakangan Ganbataar menempa klan-klan yang tercerai-berai menjadi kekuatan militer yang berdisiplin.",
  "lore.VIII.t": "Tanah-Tanah Strategis",
  "lore.VIII.s": "Peta sebagai senjata",
  "lore.VIII.x": "Penyeberangan sungai, celah pegunungan tinggi, dan lahan basah merupakan aset strategis yang menentukan. Jembatan mengamankan perdagangan dan penjarahan, celah gunung menghentikan bala tentara selatan, dan lahan basah yang subur tetap menjadi tanah rebutan tempat klan-klan saingan berburu dan saling menyergap.",
  "lore.IX.t": "Penyergapan",
  "lore.IX.s": "Jebakan hutan dan pelajaran dari pengepungan",
  "lore.IX.x": "Batu memancing pasukan selatan ke dalam pura-pura mundur, lalu menghantam sayap mereka dengan panah berapi. Para pengintai menyabotase benteng dari dalam, sementara para insinyur merobohkan tembok luar. Pelajarannya jelas: kavaleri ringan menguasai medan terbuka, tetapi pengepungan panjang menuntut disiplin dan mesin yang memadai.",
  "lore.X.t": "Serigala",
  "lore.X.s": "Penjinak kegelapan dan keseimbangan",
  "lore.X.x": "Seorang pengunjung kosmis yang gelap memilih rupa seekor serigala. Meski energi lahiriahnya membawa kehancuran, intinya adalah cahaya murni. Serigala itu menjadi lambang keseimbangan: tiada cahaya tanpa kegelapan, dan cinta memulai kerja yang dipertahankan oleh keseimbangan.",
  "lore.XI.t": "Upacara dan Kepahlawanan",
  "lore.XI.s": "Nyanyian tenggorokan, pemakaman, dan sumpah Temüü",
  "lore.XI.x": "Seusai pertempuran, para syaman menenangkan arwah, menyucikan medan, dan menguburkan yang mati. Melalui nyanyian tenggorokan, mereka menghibur para tabib dan mereka yang sekarat. Sesudah itu Qorchi mendorong Temüü yang masih muda menuju duel terbuka melawan ayah tirannya, menempatkannya di jalan untuk mempersatukan klan-klan.",
  "lore.XII.t": "Pertengkaran Keluarga",
  "lore.XII.s": "Duel dan bangkitnya kekuasaan",
  "lore.XII.x": "Temüü menantang Ganbataar dan mengalahkannya dalam duel yang brutal. Setelah itu ia berbalik ke barat, menyingkirkan para pemimpin perang lama, dan memilih kemampuan di atas darah serta dendam. Ia memerintahkan pembangunan kota administrasi pertama di antara timur dan barat.",
  "lore.XIII.t": "Peralihan Kekuasaan",
  "lore.XIII.s": "Perang penyatuan dan taktik baru",
  "lore.XIII.x": "Temüü menyatukan klan-klan melalui disiplin, dinding perisai, pemanah berkuda, mesin kepung, dan serangan penentu ke pusat musuh. Penjarahan memberi tempat kepada penaklukan, hukum, perdagangan, dan satu pemerintahan pusat.",
  "lore.XIV.t": "Pembangunan Kembali",
  "lore.XIV.s": "Ulanbataar dan ancaman selatan",
  "lore.XIV.x": "Ibu kota baru bangkit di Ulanbataar. Temüü memberi ganjaran kepada prajurit dan petani, memenjarakan syaman ambisius Qorchi, dan melarang kekerasan terhadap perempuan serta anak-anak. Lalu datanglah seorang utusan selatan dengan ancaman yang disokong oleh bala tentara sejuta orang.",
  "lore.XV.t": "Hidup Baru, Kebiasaan Lama",
  "lore.XV.s": "Perjalanan menyerang bala tentara selatan",
  "lore.XV.x": "Temüü berjanji akan memimpin dari barisan depan, tetapi perarakan itu membawa penyergapan, sabotase, dan sungai yang tertutup kapal-kapal berantai. Pasukan padang stepa memiliki kecepatan dan disiplin; kekaisaran selatan memiliki jumlah, senjata api, dan posisi bertahan yang diperkuat.",
  "lore.XVI.t": "Perang yang Tak Berkesudahan",
  "lore.XVI.s": "Jembatan, sungai, dan kebuntuan",
  "lore.XVI.x": "Para insinyur membangun jembatan di bawah hujan panah dan kavaleri memanfaatkan pura-pura mundur untuk mematahkan barisan selatan. Namun tembok pesisir tidak dapat direbut. Pelajaran terakhir adalah menggabungkan kekuatan militer dengan pemerintahan otonom, perdagangan, dan penghormatan terhadap pengetahuan selatan.",
  "lore.XVII.t": "Setiap Malam Berakhir dalam Fajar",
  "lore.XVII.s": "Perdamaian, kepulangan, dan sebuah dinasti",
  "lore.XVII.x": "Lelah oleh perang, Temüü kembali ke Ulanbataar dan memilih perdamaian. Ia menghendaki penduduk bertambah, tentara dipercayakan kepada para perwira yang lebih muda, dan kekaisaran menjadi kuat melalui persatuan alih-alih penaklukan yang tak berkesudahan.",
  "lore.XVIII.t": "Penutup",
  "lore.XVIII.s": "Kisah-kisah yang mengikat kita",
  "lore.XVIII.x": "Tidak ada tentara yang tak terkalahkan dan tidak ada dinasti yang bertahan selamanya. Manusia bersifat kesukuan dan keras, tetapi juga sosial, politis, penuh empati, dan mampu melampaui dirinya sendiri. Yang mengikat kita bukanlah kemenangan atau kekalahan, melainkan kisah-kisah yang kita bagi.",
  "rule.0.t": "Perburuan lestari",
  "rule.0.x": "Ambillah dari alam tanpa menghancurkannya, jika tidak Handgai akan memalingkan wajahnya.",
  "rule.1.t": "Perlindungan lemak hewan",
  "rule.1.x": "Pakaian dan baju zirah disegel terhadap dingin yang membunuh, angin, dan kelembapan.",
  "rule.2.t": "Kesetaraan radikal",
  "rule.2.x": "Makanan dan sumber daya dibagi di dalam klan; penimbunan berujung pada pengasingan.",
  "rule.3.t": "Ancaman pengasingan",
  "rule.3.x": "Melanggar hukum suku berarti kematian pasti di belantara, tempat bertahan hidup menuntut kerja sama.",
  "rule.4.t": "Gilda pengintai",
  "rule.4.x": "Para pengintai adalah pembuat peta elite dan penjaga jalur dagang rahasia.",
  "rule.5.t": "Syaman",
  "rule.5.x": "Para syaman menafsirkan arwah, menyembuhkan orang sakit, membaca mimpi, dan menasihati para penguasa.",
  "pan.0.n": "Handgai, Sang Rusa Agung",
  "pan.0.x": "Pencipta tertinggi yang menuntun kehidupan dan takut akan apa yang mungkin dihancurkan umat manusia.",
  "pan.1.n": "Sang Elang",
  "pan.1.x": "Mata langit dan hati nurani ilahi.",
  "pan.2.n": "Sang Beruang",
  "pan.2.x": "Kekuatan mentah yang diseimbangkan oleh pengendalian diri mutlak.",
  "pan.3.n": "Sang Burung Hantu",
  "pan.3.x": "Pantangan mutlak; melukainya adalah kejahatan rohani.",
  "pan.4.n": "Sang Rubah",
  "pan.4.x": "Pertanda bencana sebelum perjalanan atau pertempuran.",
  "pan.5.n": "Sang Tikus",
  "pan.5.x": "Penyakit, pembusukan, dan pengkhianatan, yang tiap tahun dilawan oleh semua klan.",
  "char.0.n": "Temüü",
  "char.0.r": "Sang pemersatu",
  "char.0.x": "Seorang anak laki-laki yang peka dan cerdas, yang mengalahkan ayah tirannya, mempersatukan klan-klan, dan memikul ketegangan antara empati dan kekerasan.",
  "char.1.n": "Ganbataar",
  "char.1.r": "Sang tiran",
  "char.1.x": "Seorang panglima perang yang mabuk dan brutal, yang memerintah keluarganya melalui ketakutan dan mati dalam duel melawan Temüü.",
  "char.2.n": "Qorchi",
  "char.2.r": "Sang syaman",
  "char.2.x": "Penafsir kekuatan-kekuatan kosmis yang membimbing Temüü menuju kekuasaan sambil diam-diam membangun pengaruhnya sendiri.",
  "char.3.n": "Bolormaa",
  "char.3.r": "Sang pembaru",
  "char.3.x": "Pembawa tulisan, ilmu, diplomasi, dan perlindungan bagi perempuan serta anak-anak.",
  "char.4.n": "Batu",
  "char.4.r": "Sang panglima",
  "char.4.x": "Seorang panglima lapangan yang pura-pura mundurnya dan penyergapan panah berapinya menjadi legenda.",
  "char.5.n": "Kaisar Langit",
  "char.5.r": "Penguasa selatan",
  "char.5.x": "Seorang penguasa angkuh dengan pasukan yang amat besar dan tembok yang tak tertembus, namun dikalahkan di medan terbuka."
};

export default translations;
