// Kronikan (Codex) käännös (pt). Avaimet vastaavat Codex.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.back": "Voltar ao jogo",
  "ui.rulebook": "Livro de Regras",
  "ui.eyebrow": "Contos da Estepe",
  "ui.title": "A Crônica das Terras de Fronteira",
  "ui.subtitle": "Livro do Mundo & Códice do Jogador",
  "ui.tagline": "Tudo o que você precisa saber sobre o mundo, seus deuses, povos, heróis e as duras leis da sobrevivência.",
  "ui.people": "Pessoas da Crônica",
  "ui.quote": "“O Grande Cervo entoou este mundo para que existisse — agora seu destino é cantado com aço, ouro e alianças.”",
  "lore.I.t": "A Canção Cósmica",
  "lore.I.s": "Handgai e o nascimento do mundo",
  "lore.I.x": "Antes de todas as coisas havia um mar sem fim. Handgai, o Grande Cervo, moldou Dengin, ergueu o céu e guiou a vida desde os menores organismos marinhos até o povo da estepe. O universo foi entoado à existência, e cada pedra, animal e pessoa continua fazendo parte dessa melodia divina.",
  "lore.II.t": "A Lei da Adversidade",
  "lore.II.s": "O sofrimento é o fogo que tempera",
  "lore.II.x": "O conforto é uma armadilha. O progresso vem por meio da dificuldade, da fome e do domínio da natureza. O sofrimento é tratado como um fogo literal que endurece a força humana, enquanto uma vida sem dificuldades produz sociedades frouxas e estagnadas.",
  "lore.III.t": "O Panteão Animal",
  "lore.III.s": "Deuses nas formas de animais sagrados",
  "lore.III.x": "Os deuses caminham pelo mundo em forma animal. A Águia é a consciência divina, o Urso é força e contenção, a Coruja é um tabu absoluto, a Raposa avisa sobre desastres, e o Rato representa doença e traição. Handgai, o Grande Cervo, é o criador supremo.",
  "lore.IV.t": "A Grande Divisão",
  "lore.IV.s": "a estepe e o império de pedra",
  "lore.IV.x": "O mundo é dividido pelo Grande Rio. No norte, clãs móveis viajam com seus rebanhos e oficinas em yurts vastas e engenhosamente construídas. No sul, um império burocrático depende de pedra, lei, papel, exércitos profissionais e fortificações imensas.",
  "lore.V.t": "Regras de Sobrevivência",
  "lore.V.s": "Leis da estepe e papéis especiais",
  "lore.V.x": "A caça deve permanecer sustentável, as roupas são vedadas contra o frio com gordura animal, e a comida é compartilhada dentro do clã. O exílio é a punição máxima. Batedores são uma elite respeitada, enquanto xamãs servem como médicos, intérpretes de sonhos e conselheiros políticos.",
  "lore.VI.t": "Os Poderes das Terras de Fronteira",
  "lore.VI.s": "Ganbataar, Bolormaa e Temüü",
  "lore.VI.x": "Ganbataar governa pelo medo e pela punição coletiva. Bolormaa traz aprendizado, diplomacia e nova tecnologia de terras distantes. Temüü, o herdeiro sensível, busca uma meritocracia fundada em interesses comuns em vez de crueldade.",
  "lore.VII.t": "As Eras",
  "lore.VII.s": "o mundo antes da guerra",
  "lore.VII.x": "A humanidade começou sob a Canção Cósmica, depois a esqueceu. O sul abraçou a agricultura e a burocracia, enquanto o norte aprendeu resistência com o frio e a escassez. Mais tarde, Ganbataar forjou os clãs dispersos em uma potência militar disciplinada.",
  "lore.VIII.t": "Terras Estratégicas",
  "lore.VIII.s": "o mapa como arma",
  "lore.VIII.x": "Travessias de rio, desfiladeiros de alta montanha e zonas úmidas são recursos estratégicos decisivos. Pontes garantem comércio e incursões, passagens montanhosas detêm exércitos do sul, e pântanos férteis seguem como terras disputadas onde clãs rivais caçam e armam emboscadas uns aos outros.",
  "lore.IX.t": "A Emboscada",
  "lore.IX.s": "A armadilha na floresta e a lição do cerco",
  "lore.IX.x": "Batu atraiu um exército do sul para uma retirada fingida e então golpeou seu flanco com flechas incendiárias. Batedores sabotaram a fortaleza por dentro, enquanto engenheiros derrubaram a muralha externa. A lição foi clara: a cavalaria leve domina o campo aberto, mas um longo cerco exige disciplina e máquinas adequadas.",
  "lore.X.t": "O Lobo",
  "lore.X.s": "O domador da escuridão e do equilíbrio",
  "lore.X.x": "Um visitante cósmico sombrio escolheu a forma de um lobo. Embora sua energia exterior trouxesse destruição, em seu núcleo havia pura luz. O lobo tornou-se um sinal de equilíbrio: não há luz sem escuridão, e o amor inicia a obra que o equilíbrio sustenta.",
  "lore.XI.t": "Cerimônia e Heroísmo",
  "lore.XI.s": "Canto gutural, sepultamento e o juramento de Temüü",
  "lore.XI.x": "Após a batalha, xamãs acalmaram espíritos, purificaram o campo e enterraram os mortos. Por meio do canto gutural, confortaram curandeiros e moribundos. Qorchi então empurrou o jovem Temüü para um duelo público com seu pai tirano, colocando-o no caminho para unir os clãs.",
  "lore.XII.t": "Uma Briga de Família",
  "lore.XII.s": "O duelo e a ascensão do poder",
  "lore.XII.x": "Temüü desafiou Ganbataar e o derrotou em um duelo brutal. Depois voltou-se para o oeste, removeu os antigos líderes de guerra e escolheu o mérito em vez do sangue e da vingança. Foi ordenada a construção da primeira cidade administrativa entre o leste e o oeste.",
  "lore.XIII.t": "A Transferência do Poder",
  "lore.XIII.s": "Guerras de unificação e uma nova tática",
  "lore.XIII.x": "Temüü uniu os clãs por meio de disciplina, muralhas de escudos, arqueiros montados, máquinas de cerco e um golpe decisivo contra o centro inimigo. As incursões cederam lugar à conquista, à lei, ao comércio e a uma única administração central.",
  "lore.XIV.t": "Reconstrução",
  "lore.XIV.s": "Ulanbataar e a ameaça do sul",
  "lore.XIV.x": "A nova capital surgiu em Ulanbataar. Temüü recompensou soldados e agricultores, aprisionou o ambicioso xamã Qorchi e proibiu a violência contra mulheres e crianças. Então chegou um emissário do sul com uma ameaça apoiada por um exército de um milhão de homens.",
  "lore.XV.t": "Uma Nova Vida, Velhos Hábitos",
  "lore.XV.s": "A marcha contra o exército do sul",
  "lore.XV.x": "Temüü prometeu liderar pela frente, mas a marcha trouxe emboscadas, sabotagem e um rio bloqueado por navios acorrentados. O exército da estepe tinha velocidade e disciplina; o império do sul tinha números, armas de fogo e posições fortificadas.",
  "lore.XVI.t": "A Guerra Sem Fim",
  "lore.XVI.s": "Pontes, o rio e o impasse",
  "lore.XVI.x": "Engenheiros construíram pontes sob fogo e a cavalaria usou retiradas fingidas para romper a linha do sul. Ainda assim, as muralhas costeiras não puderam ser tomadas. A lição final foi combinar força militar com administração autônoma, comércio e respeito pelo conhecimento do sul.",
  "lore.XVII.t": "Toda Noite Termina na Aurora",
  "lore.XVII.s": "Paz, retorno e uma dinastia",
  "lore.XVII.x": "Exausto pela guerra, Temüü voltou a Ulanbataar e escolheu a paz. Ele queria que a população crescesse, que os exércitos fossem confiados a oficiais mais jovens e que o império se tornasse forte pela unidade em vez de pela conquista sem fim.",
  "lore.XVIII.t": "Posfácio",
  "lore.XVIII.s": "As histórias que nos unem",
  "lore.XVIII.x": "Nenhum exército é invencível e nenhuma dinastia dura para sempre. As pessoas são tribais e violentas, mas também sociais, políticas, empáticas e capazes de superar a si mesmas. O que nos une não é a vitória nem a derrota, mas as histórias que compartilhamos.",
  "rule.0.t": "Caça sustentável",
  "rule.0.x": "Tire da natureza sem destruí-la, ou Handgai desviará o olhar.",
  "rule.1.t": "Proteção com gordura animal",
  "rule.1.x": "Roupas e armaduras são vedadas contra o frio mortal, o vento e a umidade.",
  "rule.2.t": "Igualdade radical",
  "rule.2.x": "Comida e recursos são compartilhados dentro do clã; acumular leva ao exílio.",
  "rule.3.t": "A ameaça do exílio",
  "rule.3.x": "Quebrar a lei tribal significa morte certa em uma natureza selvagem onde sobreviver exige cooperação.",
  "rule.4.t": "Guildas de batedores",
  "rule.4.x": "Batedores são cartógrafos de elite e guardiões de rotas comerciais ocultas.",
  "rule.5.t": "Xamãs",
  "rule.5.x": "Xamãs interpretam espíritos, curam os doentes, leem sonhos e aconselham governantes.",
  "pan.0.n": "Handgai, o Grande Cervo",
  "pan.0.x": "O criador supremo, que guia a vida e teme aquilo que a humanidade pode destruir.",
  "pan.1.n": "A Águia",
  "pan.1.x": "Os olhos do céu e a consciência divina.",
  "pan.2.n": "O Urso",
  "pan.2.x": "Força bruta equilibrada por contenção absoluta.",
  "pan.3.n": "A Coruja",
  "pan.3.x": "Um tabu absoluto; ferir uma é um crime espiritual.",
  "pan.4.n": "A Raposa",
  "pan.4.x": "Um presságio de desastre antes de uma jornada ou batalha.",
  "pan.5.n": "O Rato",
  "pan.5.x": "Doença, podridão e traição, combatidas por todos os clãs uma vez por ano.",
  "char.0.n": "Temüü",
  "char.0.r": "O unificador",
  "char.0.x": "Um rapaz sensível e inteligente que derrota o pai tirano, une os clãs e carrega a tensão entre empatia e violência.",
  "char.1.n": "Ganbataar",
  "char.1.r": "O tirano",
  "char.1.x": "Um senhor da guerra bêbado e violento que governa a família pelo medo e morre em um duelo com Temüü.",
  "char.2.n": "Qorchi",
  "char.2.r": "O xamã",
  "char.2.x": "Intérprete das forças cósmicas que guia Temüü rumo ao poder enquanto, em silêncio, constrói sua própria influência.",
  "char.3.n": "Bolormaa",
  "char.3.r": "A reformadora",
  "char.3.x": "A portadora da escrita, do saber, da diplomacia e de proteções para mulheres e crianças.",
  "char.4.n": "Batu",
  "char.4.r": "O comandante",
  "char.4.x": "Um comandante de campo cuja retirada fingida e emboscada com flechas incendiárias se tornam lendárias.",
  "char.5.n": "O Imperador Celestial",
  "char.5.r": "O governante do sul",
  "char.5.x": "Um governante orgulhoso com um exército imenso e muralhas inexpugnáveis, derrotado em campo aberto."
};

export default translations;
