// Sääntökirjan käännös (de). Avaimet vastaavat Ohjekirja.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.chapter": "Kapitel",
  "ui.title": "Tales of the Steppe — Regelbuch",
  "ui.subtitle": "Geschichte der Steppe · Jahr 1206 · paragrafenweise",
  "ui.print": "Drucken",
  "ui.toGame": "Zum Spiel",
  "ui.search": "Kapitel suchen…",
  "ui.footer": "Tales of the Steppe — Geschichte der Steppe · Regelbuch · Jahr 1206",
  "ui.backToTop": "↑ Nach oben",
  "ui.returnToGame": "Zurück zum Spiel",
  "ch.johdanto": "Einführung und Spielkonzept",
  "p.1.1": "Tales of the Steppe (Story of the Steppe) ist ein rundenbasiertes Strategiespiel, das im Jahr 1206 n. Chr. spielt — in jenem Moment, als Temüjin zu Dschingis Khan ausgerufen wurde und die Völker der Steppe die Welt erschütterten. Der Spieler führt eine von vier Großmächten und strebt den Sieg auf einem von fünf verschiedenen Wegen an (Kapitel III).",
  "p.1.2": "Es ist ein Einzelspiel gegen KI-Gegner. Jedes Jahr ist ein Zug, der in fünf Phasen unterteilt ist (Kapitel VI). Der Spieler kontrolliert Provinzen (Dörfer), sammelt Ressourcen, errichtet Gebäude, rekrutiert Armeen, spielt Karten und betreibt Diplomatie und Krieg.",
  "p.1.3": "Dieses Regelbuch beschreibt die Spielregeln genau so, wie sie umgesetzt sind. Zahlenwerte (Kosten, Boni, Schwellenwerte) sind verbindlich und entsprechen der Spiellogik. Im Konfliktfall ist das Spiel selbst maßgeblich, doch Ziel ist, dass dieses Buch und das Spiel übereinstimmen.",
  "ch.kasitteet": "Grundbegriffe und Terminologie",
  "p.2.1": "**Provinz (Dorf):** ein Hexfeld auf der Karte. Jede Provinz hat einen Besitzer (eine Fraktion oder neutral), Gelände, eine Grundentwicklung, möglicherweise ein Handelsgut und eine Befestigungsstufe.",
  "p.2.2": "**Fraktion:** ein spielbares Reich. Es stehen vier Fraktionen zur Verfügung: die Mongolen, Song (China), die Rus-Fürstentümer und Khwarezm (Persien).",
  "p.2.3": "**Ressourcen:** Gold, Nahrung, Pferde, Mannstärke und Handwerker. Dazu kommen zwei an Prestige erinnernde Werte: Einfluss und Prestige.",
  "p.2.4": "**Einfluss:** diplomatisches Gewicht, erzeugt durch Handelsknoten, den Besitz der Hauptstadt, Allianzen und Wunder. Der Zähler für den Diplomatiesieg.",
  "p.2.5": "**Prestige:** kulturelles Ansehen, das nur durch Wunder (ein Gebäude) erzeugt wird. Der Zähler für den Kultursieg.",
  "p.2.6": "**Armee:** ein Truppenstapel mit Kavallerie, Infanterie und gegebenenfalls Belagerungseinheiten sowie Moral und Versorgung.",
  "p.2.7": "**Seidenstraße:** eine Handelsroute quer über die Karte; die Provinzen entlang dieser Route sind Handelsknoten, die zusätzliches Einkommen und Einfluss erzeugen (Kapitel VIII).",
  "ch.voitto": "Siegbedingungen — fünf Wege",
  "p.3.1": "Das Spiel endet mit einem Sieg, wenn am Ende des Zuges eines Spielers eine der folgenden fünf Bedingungen erfüllt ist. Die Bedingungen werden am Ende jedes Zuges geprüft.",
  "p.3.2": "**Militärsieg:** Erobere die Hauptstadt jeder feindlichen Fraktion — ODER kontrolliere mindestens **30 Provinzen** (etwa 40% der Karte).",
  "p.3.3": "**Wirtschaftssieg:** drei Bedingungen zugleich: (a) mindestens **500 Gold** in der Schatzkammer, (b) du kontrollierst eine **Mehrheit der Handelsknoten der Seidenstraße** (mehr als die Hälfte), und (c) du hältst die Goldschwelle **mindestens 3 aufeinanderfolgende Züge lang** (die Serie wird zurückgesetzt, wenn Gold unter 500 fällt).",
  "p.3.4": "**Technologiesieg:** Spiele **mindestens 5 Technologiekarten** (permanente Technologiekarten).",
  "p.3.5": "**Diplomatiesieg:** Erreiche **mindestens 100 Einfluss** — ODER bilde mit jeder überlebenden feindlichen Fraktion eine Allianz (mindestens 2 Verbündete).",
  "p.3.6": "**Kultursieg:** Sammle durch den Bau von Wundern in deiner Hauptstadt **mindestens 60 Prestige** an.",
  "p.3.7": "**Niederlage:** Der Spieler verliert, wenn er alle seine Provinzen und alle seine Armeen verliert. Die KI kann ebenfalls durch Militär- oder Wirtschaftssieg gewinnen, wodurch das Spiel endet.",
  "ch.fraktiot": "Fraktionen und Startaufstellung",
  "p.4.1": "Das Spiel hat vier Fraktionen, die in den Ecken des Spielbretts positioniert sind: die Rus oben links, die Mongolen oben rechts, Song unten rechts und Khwarezm unten links. Die Mitte der Karte ist neutral.",
  "p.4.2": "Jede Fraktion beginnt mit 12 Provinzen, einer Hauptstadt und einer Gründerarmee unter Führung des Stammeshäuptlings (Kapitel XIII). Startressourcen und Sonderboni sind unten aufgeführt.",
  "t1.h.0": "Fraktion",
  "t1.h.1": "Farbe",
  "t1.h.2": "Herrscher",
  "t1.h.3": "Hauptstadt",
  "t1.h.4": "Gold",
  "t1.h.5": "Mannstärke",
  "t1.h.6": "Pferde",
  "t1.h.7": "Sonderboni",
  "t1.r.0.0": "Mongolenreich",
  "t1.r.0.1": "🟡 gelb",
  "t1.r.0.2": "Dschingis Khan",
  "t1.r.0.3": "Karakorum",
  "t1.r.0.7": "Kavallerie +30%, Belagerung +20% · aggressiv",
  "t1.r.1.0": "Song-Dynastie",
  "t1.r.1.1": "🟢 grün",
  "t1.r.1.2": "Kaiser Ningzong",
  "t1.r.1.3": "Lin'an (Hangzhou)",
  "t1.r.1.7": "Steuern +30%, Kavallerie −10%, Belagerung −10% · handelsorientiert",
  "t1.r.2.0": "Rus-Fürstentümer",
  "t1.r.2.1": "⚪ grau",
  "t1.r.2.2": "Großfürst",
  "t1.r.2.3": "Nowgorod",
  "t1.r.2.7": "Steuern +10%, Belagerung +10% · defensiv",
  "t1.r.3.0": "Reich von Khwarezm",
  "t1.r.3.1": "🟣 violett",
  "t1.r.3.2": "Schah Muhammad II",
  "t1.r.3.3": "Samarkand",
  "t1.r.3.7": "Kavallerie +10%, Steuern +20%, Belagerung +10% · expansionistisch",
  "p.4.3": "Anfangsbeziehungen: Alle Fraktionen beginnen einander gegenüber neutral (Beziehung 0, Vertrauen 50, Bedrohung 30). Ausnahme: Die anderen starten mit angeborenem Misstrauen gegenüber den Mongolen (Beziehung −20, Bedrohung 60), da die Mongolen eine aggressive Expansionsmacht sind.",
  "p.4.4": "Startvorrat (für alle Spieler gleich): 10 Nahrung, 3 Handwerker, 0 Einfluss, 0 Prestige. Starthand: 5 Karten (Kapitel XIV).",
  "ch.kartta": "Karte, Provinzen und Gelände",
  "p.5.1": "Die Karte ist ein Hexraster, in dem jedes vollständige Hexfeld ein Dorf enthält. Die Dörfer sind zwischen den Fraktionen (Ränder/Ecken) und Neutralen (Mitte) aufgeteilt. Nachbarschaft wird mit einem odd-r-Hexlayout berechnet: Jedes Feld grenzt an höchstens sechs Nachbarn.",
  "p.5.2": "Das Gelände beeinflusst Bewegungskosten, Verteidigung, Versorgungslimit und Besteuerung. Die Bewegungskosten hängen vom Einheitentyp ab (Infanterie/Kavallerie/Belagerung). Der Verteidigungsbonus wird zur Kampfstärke des Verteidigers addiert (Kapitel XI).",
  "t2.h.0": "Gelände",
  "t2.h.1": "Infanterie",
  "t2.h.2": "Kavallerie",
  "t2.h.3": "Belagerung",
  "t2.h.4": "Verteidigung",
  "t2.h.5": "Versorgung",
  "t2.h.6": "Steuerfaktor",
  "t2.r.0.0": "🌾 Steppe",
  "t2.r.1.0": "🌿 Grasland",
  "t2.r.2.0": "🌾 Ackerland",
  "t2.r.3.0": "🌲 Wald",
  "t2.r.4.0": "⛰️ Hügel",
  "t2.r.5.0": "⛰️ Gebirge",
  "t2.r.6.0": "🏜️ Wüste",
  "t2.r.7.0": "🌿 Sumpf",
  "t2.r.8.0": "🌲 Taiga",
  "t2.r.9.0": "❄️ Tundra",
  "p.5.3": "Ackerland und Grasland erzeugen Nahrung; Steppe und Pferdeprovinzen erzeugen Pferde; Ackerland und Hügel erzeugen Handwerker (Kapitel VII). Gebirge und Hügel bieten die beste Verteidigung, verlangsamen aber die Bewegung.",
  "ch.vuoro": "Zugablauf (5 Phasen)",
  "p.6.1": "Jeder Zug (jedes Jahr) durchläuft fünf Phasen in fester Reihenfolge. Mit der Schaltfläche „Next“ wechselst du von einer Phase zur nächsten.",
  "p.6.2": "**1. Ressourcen:** Sammle Einkommen aus kontrollierten Provinzen (Gold, Mannstärke, Nahrung, Pferde, Handwerker) sowie Einfluss und Prestige. Das Einkommen wird mit den Formeln aus Kapitel VII berechnet.",
  "p.6.3": "**2. Karten:** Ziehe 1 Karte vom Stapel (die Starthand ist 5) und spiele beliebige Karten aus deiner Hand. Die Karteneffekte stehen in Kapitel XIV.",
  "p.6.4": "**3. Angriff:** Bewege Armeen in benachbarte Provinzen oder löse Angriffe gegen feindlich oder neutral kontrollierte Provinzen aus (Kapitel XI).",
  "p.6.5": "**4. Bauen:** Errichte Gebäude in deinen eigenen Provinzen und rekrutiere Truppen (Kapitel IX–X).",
  "p.6.6": "**5. Zug beenden:** Die KI-Gegner führen ihre Züge aus, Belagerungen schreiten voran, permanente Boni werden aktualisiert, Siegbedingungen werden geprüft und ein neues Jahr beginnt.",
  "ch.talous": "Ressourcen und Wirtschaft",
  "p.7.1": "**Goldeinkommen** = (Grundsteuer der Provinzen + Seidenstraßenbonus + Marktbonus + Brückenbonus) × Hauptstadt-Multiplikator. Ein Markt bringt jeweils +3 Gold, eine Seidenstraßenbrücke jeweils +2 Gold. Geht die Hauptstadt verloren, beträgt der Multiplikator 0.5 (Einkommen halbiert), sonst 1.0.",
  "p.7.2": "**Frühspielschub:** In den Zügen 1–4 werden dem Goldeinkommen +4 hinzugefügt, um den frühen Ausbau zu beschleunigen.",
  "p.7.3": "**Mannstärke** = 30% der gemeinsamen Grundmannstärke der Provinzen (abgerundet).",
  "p.7.4": "**Nahrung** = −1 pro Armee (Unterhalt) + 0.5 × Ackerland-/Graslandprovinzen + 2 × Lager. Nahrung kann eine negative Veränderung sein; sie wird für den Unterhalt der Truppen verbraucht.",
  "p.7.5": "**Pferde** = Anzahl der Steppen-/Pferdeprovinzen + Anzahl der Ställe (1 pro Stall).",
  "p.7.6": "**Handwerker** = 0.5 × (Ackerland- und Hügelprovinzen) + Anzahl der Werkstätten. Kontrollierst du mindestens 3 Provinzen, erhältst du mindestens 1 Handwerker pro Zug.",
  "p.7.7": "**Einfluss/Zug** = Handelsknoten (1 je Knoten) + gehaltene Hauptstadt (2) + Allianzen (2 je Allianz) + Wunder (2 je Wunder).",
  "p.7.8": "**Prestige/Zug** = 3 × Anzahl der Wunder.",
  "ch.silkkitie": "Die Seidenstraße und Handelsknoten",
  "p.8.1": "Die Seidenstraße ist eine Handelsroute, die über die mittlere Reihe der Karte verläuft. Die Provinzen entlang dieser Route sind Handelsknoten (mit einer Seidenstraßenflagge markiert).",
  "p.8.2": "**Seidenstraßenbonus** = Grundsteuer der Handelsknoten + 2 × Knoten, die das Handelsgut Seide erzeugen + **Kettenbonus**. Der Kettenbonus belohnt die Kontrolle ununterbrochener Knotenzüge: Jeder verbundene Cluster (Größe > 1) gewährt ungefähr 1.6 × (Clustergröße^1.45) zusätzliches Gold. Ein einzelner ununterbrochener Abschnitt der Seidenstraße ist daher weit wertvoller als verstreute Haltepunkte.",
  "p.8.3": "Die Kontrolle über die Mehrheit der Seidenstraße (mehr als die Hälfte aller Knoten) ist eine Voraussetzung für den Wirtschaftssieg (§ 3.3) und erzeugt erheblichen Einfluss (§ 7.7).",
  "ch.rakennukset": "Gebäude",
  "p.9.1": "Gebäude werden während der Bauphase in deinen eigenen Provinzen errichtet. Sie kosten Gold und oft Handwerker. Jedes Gebäude gewährt einen permanenten Vorteil.",
  "t3.h.0": "Gebäude",
  "t3.h.1": "Gold",
  "t3.h.2": "Handwerker",
  "t3.h.3": "Effekt",
  "t3.r.0.0": "⛺ Lager",
  "t3.r.0.3": "+2 Nahrung/Zug; Rekrutierungspunkt für Infanterie",
  "t3.r.1.0": "🏪 Markt",
  "t3.r.1.3": "+3 Gold/Zug",
  "t3.r.2.0": "🌉 Brücke",
  "t3.r.2.3": "+2 Gold/Zug an der Seidenstraße; Übergang für Karawanen",
  "t3.r.3.0": "🔨 Werkstatt",
  "t3.r.3.3": "+1 Handwerker/Zug; rekrutierte Truppen erhalten +10 Moral",
  "t3.r.4.0": "🐎 Stall",
  "t3.r.4.3": "+1 Pferd/Zug; Rekrutierungspunkt für Kavallerie",
  "t3.r.5.0": "🏯 Festung",
  "t3.r.5.3": "+3 Verteidigung (erhöht die Befestigungsstufe)",
  "t3.r.6.0": "🏛️ Wunder",
  "t3.r.6.3": "Nur Hauptstadt: +Prestige und +Einfluss/Zug",
  "p.9.2": "**Rolle der Gebäude bei der Rekrutierung:** Ein Lager schaltet die Rekrutierung von Infanterie frei, ein Stall schaltet die Rekrutierung von Kavallerie frei. In der Hauptstadt können beide ohne spezielles Gebäude rekrutiert werden (Kapitel X).",
  "p.9.3": "**Wunder** sind die einzige Quelle von Prestige und damit der Schlüssel zum Kultursieg. Sie können nur in der Hauptstadt gebaut werden.",
  "ch.armeijat": "Armeen, Rekrutierung und Bewegung",
  "p.10.1": "**Rekrutierungskosten:** Infanterie kostet **10 Gold und 5 Nahrung**. Kavallerie kostet **20 Gold, 5 Pferde und 10 Nahrung**.",
  "p.10.2": "**Rekrutierungsvoraussetzungen:** Infanterie kann aus einer Provinz mit einem Lager (oder der Hauptstadt) rekrutiert werden; Kavallerie aus einer Provinz mit einem Stall (oder der Hauptstadt). Geht die Hauptstadt verloren, wird die Rekrutierung ausgesetzt, bis sie zurückerobert wird.",
  "p.10.3": "**Zusammensetzung des Stapels:** Eine Infanterierekrutierung erzeugt 5 Infanterie (+ bis zu 2 Kavallerie, abhängig von verfügbaren Pferden). Eine Kavallerierekrutierung erzeugt Kavallerie in Höhe von min(4 + Ställe, Pferde/2), der Rest wird zu Infanterie (mindestens 2). Eine Werkstatt verleiht neuen Truppen +10 Moral (Grundmoral 70, mit Werkstatt 80).",
  "p.10.4": "**Bewegung:** Eine Armee bewegt sich in eine benachbarte Provinz, indem sie die Bewegungskosten des Geländes bezahlt (Kapitel V). Belagerungseinheiten verwenden die Belagerungskosten; andernfalls verwendet ein kavallerielastiger Stapel (Kavallerie ≥ Infanterie) die Kavalleriekosten, und infanterielastige Stapel verwenden die Infanteriekosten.",
  "p.10.5": "**Moral und Versorgung:** Jede Armee hat Moral (0–100) und Versorgung. Ein siegreicher Kampf erhöht die Moral (+5). Die Nähe zum Stammeshäuptling erhöht die Moral (Kapitel XIII).",
  "ch.taistelu": "Kampfsystem",
  "p.11.1": "**Kampfstärke:** Stärke des Angreifers = 2 × Kavallerie + Infanterie + Belagerung + Angriffsboni. Stärke des Verteidigers = 2 × Kavallerie + Infanterie. Kavallerie zählt in der rohen Stärke also doppelt.",
  "p.11.2": "**Würfelwurf:** Beide Seiten würfeln 1d6. Wert des Angreifers = Stärke + Würfel. Wert des Verteidigers = Stärke + Würfel + 2 × Verteidigungsbonus des Geländes + 3 × effektive Befestigungsstufe.",
  "p.11.3": "**Belagerung schwächt Mauern:** Effektive Befestigungsstufe = Befestigungsstufe − 0.5 × Belagerungseinheiten (nicht unter 0). Belagerungseinheiten zermürben also die Verteidigung.",
  "p.11.4": "**Auflösung:** Wer den höheren Wert erzielt, gewinnt. Wenn der Angreifer gewinnt, erleidet der Verteidiger Schaden (Stärke des Angreifers − Verteidigungsboni); verliert der Angreifer, erleidet der Angreifer Schaden in Höhe der Stärke des Verteidigers.",
  "p.11.5": "**Verteilung der Verluste:** Schaden trifft zuerst die Infanterie; verbleibender Schaden entfernt Kavallerie mit halber Wirksamkeit (Kavallerie ist robuster). Der Verteidiger wird zerstört, wenn er seine gesamte Kavallerie und Infanterie verliert.",
  "p.11.6": "**Karteneffekte:** Gespielte Strategiekarten können Angriffs-, Verteidigungs- oder Bewegungsboni gewähren, die zur Stärkeberechnung hinzugefügt werden (Kapitel XIV).",
  "ch.piiritys": "Belagerung und Hauptstädte",
  "p.12.1": "**Blockade:** Wenn eine Provinz vollständig von feindlich kontrollierten Nachbarn umgeben ist, wird sie belagert und der Belagerungsbalken wächst Zug für Zug.",
  "p.12.2": "**Auswirkung der Belagerung:** Hat die Provinz eine Festung, sinkt ihre Stufe unter Belagerung um −1/Zug. Gibt es keine Festung, verliert der Besitzer 5 Gold/Zug (die Versorgung ist abgeschnitten). Der Belagerungsbalken wird zurückgesetzt, sobald die Blockade aufgehoben wird.",
  "p.12.3": "**Verlorene Hauptstadt:** Wenn sich deine Hauptstadt in feindlicher Hand befindet, wird (a) das gesamte Goldeinkommen halbiert (§ 7.1) und (b) die Rekrutierung ausgesetzt (§ 10.2), bis die Hauptstadt zurückerobert wird.",
  "p.12.4": "**Feindliche Hauptstädte** sind der Schlüssel zum Militärsieg: Die Eroberung jeder feindlichen Hauptstadt beendet das Spiel mit einem Sieg (§ 3.2).",
  "ch.paallikko": "Stammeshäuptling",
  "p.13.1": "Die Gründerarmee jeder Fraktion (die „Haupt“-Armee) trägt den Stammeshäuptling. Der Häuptling ist sowohl Anführer als auch Quelle der Moral.",
  "p.13.2": "**Moralbonus:** Armeen in derselben Provinz wie der Häuptling erhalten +5 Moral, und Armeen in benachbarten Provinzen erhalten einen kleineren Bonus. Boni werden am Ende des Zuges aktualisiert.",
  "p.13.3": "**Tod des Häuptlings:** Wenn die Gründerarmee des Spielers zerstört wird, folgt eine einmalige Strafe: **−30 Gold**, **−15 Einfluss**, und die Moral aller Truppen des Spielers sinkt (−10). Dies geschieht nur einmal.",
  "p.13.4": "Den Häuptling zu schützen, ist daher strategisch wichtig: Schicke die Gründerarmee früh nicht in unnötige Risiken.",
  "ch.kortit": "Kartensystem",
  "p.14.1": "**Kartenziehen:** Das Spiel beginnt mit einer Hand von 5 Karten; während der Kartenphase ziehst du 1 neue Karte pro Zug. Gespielte Karten kommen auf den Ablagestapel (außer permanente Technologiekarten).",
  "p.14.2": "**Kartentypen:** Strategie (Kampfboni), Technologie (permanente Boni; 5 gespielte = Technologiesieg), Diplomatie (Beziehungen) und Ressourcen (Gold/Nahrung/Pferde/Handwerker).",
  "p.14.3": "**Seltenheiten:** gewöhnlich, ungewöhnlich, selten, legendär. Seltenere Karten sind mächtiger, erscheinen aber seltener.",
  "p.14.4": "**Dauer der Effekte:** Ressourcenkarten wirken sofort (Gold/Nahrung/Pferde/Handwerker werden dem Vorrat hinzugefügt). Angriffs-/Verteidigungsboni halten eine festgelegte Dauer an (oft nur diesen Zug); ein Bewegungsbonus fügt sofort Bewegungspunkte hinzu. Permanente Angriffs-/Verteidigungskarten (Technologie) bleiben für den Rest des Spiels wirksam.",
  "p.14.5": "Karten erscheinen illustriert im Kartenfeld am unteren Rand der Spielansicht. Das Feld kann vergrößert oder verkleinert werden, indem seine obere Kante gezogen wird; die Karten werden immer so skaliert, dass sie vollständig sichtbar bleiben.",
  "ch.diplomatia": "Diplomatie",
  "p.15.1": "**Beziehungen:** Jedes Fraktionspaar hat einen Beziehungswert, Vertrauen, Bedrohung und Grenzreibung. Verträge verändern diese Werte.",
  "p.15.2": "**Vertragsarten:** friedlich — Nichtangriff, Frieden, Waffenstillstand und Allianz; sowie kriegsbezogen — formeller Krieg (war_formal) und Überraschungsangriff (war_surprise).",
  "p.15.3": "**Allianz** erzeugt +2 Einfluss/Zug (§ 7.7). Eine Allianz mit jedem überlebenden Feind (mindestens 2 Verbündete) ist ein Weg zum Diplomatiesieg (§ 3.5).",
  "p.15.4": "**Kriegserklärung:** Ein formeller Krieg wird in einem festgelegten Zug aktiv und lässt Beziehung (−90) und Vertrauen (0) abstürzen, während die Bedrohung steigt (+30). Die Mongolen tragen bereits von Beginn an eine höhere Anfangsbedrohung (§ 4.3).",
  "ch.kauppa": "Handelsgüter",
  "p.16.1": "Einige Provinzen erzeugen ein Handelsgut, das seinem Besitzer einen permanenten Vorteil gewährt. Der Wert beschreibt den relativen Handelswert des Gutes.",
  "t4.h.0": "Gut",
  "t4.h.1": "Wert",
  "t4.h.2": "Effekt",
  "t4.r.0.0": "🪙 Gold",
  "t4.r.0.2": "+3 Gold/Zug",
  "t4.r.1.0": "🧣 Seide",
  "t4.r.1.2": "+3 Gold/Zug (verstärkt die Seidenstraße)",
  "t4.r.2.0": "💎 Edelsteine",
  "t4.r.2.2": "+2 Gold/Zug und +1 Moral",
  "t4.r.3.0": "🌶️ Gewürze",
  "t4.r.3.2": "+2 Gold/Zug",
  "t4.r.4.0": "🧥 Pelze",
  "t4.r.4.2": "+1 Versorgung und +1 Moral",
  "t4.r.5.0": "🐴 Pferde",
  "t4.r.5.2": "Kavallerierekrutierung +2",
  "t4.r.6.0": "⚔️ Eisen",
  "t4.r.6.2": "−20% Einheitskosten",
  "t4.r.7.0": "🧂 Salz",
  "t4.r.7.2": "+1 Versorgung",
  "t4.r.8.0": "🌾 Getreide",
  "t4.r.8.2": "+2 Mannstärke",
  "t4.r.9.0": "🐄 Vieh",
  "t4.r.9.2": "+1 Mannstärke, +1 Versorgung",
  "ch.tekoaly": "Künstliche Intelligenz (KI)",
  "p.17.1": "Am Ende eines Zuges handelt jede KI-Fraktion entsprechend ihrer Persönlichkeit: die aggressive (Mongolen) expandiert und greift an, die handelsorientierte (Song) konzentriert sich auf die Wirtschaft, die defensive (Rus) befestigt sich, und die expansionistische (Khwarezm) nimmt neutrale Provinzen ein.",
  "p.17.2": "Die KI kann unter denselben Bedingungen wie der Spieler durch Militär- oder Wirtschaftssieg gewinnen. Die Züge der KI werden in den Benachrichtigungen zum Zugende angezeigt.",
  "p.17.3": "Die KI berücksichtigt Bedrohungs- und Beziehungswerte: Hohe Bedrohung erhöht die Wahrscheinlichkeit eines Angriffs. Die hohe Anfangsbedrohung der Mongolen macht sie zu einem wahrscheinlichen Aggressor.",
  "ch.strategia": "Strategietipps",
  "p.18.1": "**Nutze den Frühspielschub:** In den Zügen 1–4 erhältst du +4 Gold/Zug. Errichte früh Märkte und Lager als Grundlage für Wirtschaft und Rekrutierung.",
  "p.18.2": "**Halte die Seidenstraße in einem ununterbrochenen Abschnitt:** Der Kettenbonus (§ 8.2) belohnt benachbarte Handelsknoten überproportional — baue einen einzigen ununterbrochenen Verlauf statt verstreuter Haltepunkte.",
  "p.18.3": "**Schütze deine Hauptstadt und deinen Häuptling:** Eine verlorene Hauptstadt halbiert das Einkommen und stoppt die Rekrutierung; der Tod des Häuptlings kostet 30 Gold und 15 Einfluss.",
  "p.18.4": "**Wähle deinen Siegpfad früh:** Für die Mongolen ist der militärische Weg natürlich (Kavallerie +30%), für Song der wirtschaftliche und kulturelle Weg (Steuern +30%), für Khwarezm die Expansion und für die Rus ein defensiver Zermürbungskrieg.",
  "p.18.5": "**Nutze das Gelände:** Verteidige in Gebirge und Hügeln (+3/+2 Verteidigung), greife mit Kavallerie in offenem Gelände an, wo Bewegung billig ist.",
  "p.18.6": "**Belagerungseinheiten gegen Mauern:** Bringe Belagerungseinheiten gegen befestigte Provinzen mit — sie schwächen die effektive Befestigungsstufe (§ 11.3)."
};

export default translations;
