// Sääntökirjan käännös (es). Avaimet vastaavat Ohjekirja.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.chapter": "Capítulo",
  "ui.title": "Relatos de la Estepa — Reglamento",
  "ui.subtitle": "Historia de la estepa · año 1206 · por artículos",
  "ui.print": "Imprimir",
  "ui.toGame": "Ir al juego",
  "ui.search": "Buscar capítulos…",
  "ui.footer": "Relatos de la Estepa — Historia de la estepa · Reglamento · año 1206",
  "ui.backToTop": "↑ Volver arriba",
  "ui.returnToGame": "Volver al juego",
  "ch.johdanto": "Introducción y concepto del juego",
  "p.1.1": "Relatos de la Estepa (Historia de la estepa) es un juego de estrategia por turnos ambientado en 1206 d. C. — el momento en que Temüjin fue proclamado Gengis Kan y los pueblos de la estepa trastocaron el mundo. El jugador dirige una de cuatro grandes potencias y busca la victoria por una de cinco vías distintas (Capítulo III).",
  "p.1.2": "Es un juego para un solo jugador contra oponentes controlados por la IA. Cada año es un turno, dividido en cinco fases (Capítulo VI). El jugador controla provincias (aldeas), reúne recursos, construye edificios, recluta ejércitos, juega cartas y lleva a cabo diplomacia y guerra.",
  "p.1.3": "Este reglamento describe las reglas del juego exactamente tal como están implementadas. Los valores numéricos (costes, bonificaciones, umbrales) son vinculantes y coinciden con la lógica del juego. En caso de conflicto, el propio juego tiene la autoridad, pero el objetivo es que este libro y el juego coincidan.",
  "ch.kasitteet": "Conceptos básicos y terminología",
  "p.2.1": "**Provincia (aldea):** una casilla hexagonal del mapa. Cada provincia tiene un propietario (una facción o un neutral), terreno, desarrollo base, un posible bien comercial y un nivel de fortificación.",
  "p.2.2": "**Facción:** un reino jugable. Hay cuatro facciones disponibles: los mongoles, Song (China), los principados rus y Khwarezm (Persia).",
  "p.2.3": "**Recursos:** oro, comida, caballos, efectivos y artesanos. Además, hay dos medidores de prestigio: influencia y prestigio.",
  "p.2.4": "**Influencia:** peso diplomático, generado por los nodos comerciales, mantener tu capital, las alianzas y las Maravillas. El medidor de la Victoria Diplomática.",
  "p.2.5": "**Prestigio:** renombre cultural, generado solo por las Maravillas (un edificio). El medidor de la Victoria Cultural.",
  "p.2.6": "**Ejército:** un grupo de unidades con caballería, infantería y posiblemente unidades de asedio, además de moral y suministro.",
  "p.2.7": "**Ruta de la Seda:** una ruta comercial que cruza el mapa; las provincias a lo largo de ella son nodos comerciales que generan ingresos e influencia adicionales (Capítulo VIII).",
  "ch.voitto": "Condiciones de victoria — cinco vías",
  "p.3.1": "La partida termina en victoria cuando cualquiera de las siguientes cinco condiciones se cumple al final del turno de un jugador. Las condiciones se comprueban al final de cada turno.",
  "p.3.2": "**Victoria Militar:** captura la capital de cada facción enemiga — O controla al menos **30 provincias** (alrededor del 40% del mapa).",
  "p.3.3": "**Victoria Económica:** tres condiciones a la vez: (a) al menos **500 de oro** en el tesoro, (b) controlas una **mayoría de los nodos comerciales de la Ruta de la Seda** (más de la mitad), y (c) mantienes el umbral de oro durante **al menos 3 turnos consecutivos** (la racha se reinicia si el oro baja de 500).",
  "p.3.4": "**Victoria Tecnológica:** juega **al menos 5 cartas de tecnología** (cartas tecnológicas permanentes).",
  "p.3.5": "**Victoria Diplomática:** alcanza **al menos 100 de influencia** — O forma una alianza con cada facción enemiga superviviente (al menos 2 aliados).",
  "p.3.6": "**Victoria Cultural:** acumula **al menos 60 de prestigio** construyendo Maravillas en tu capital.",
  "p.3.7": "**Derrota:** el jugador pierde si pierde todas sus provincias y todos sus ejércitos. La IA también puede ganar por victoria militar o económica, lo que pone fin a la partida.",
  "ch.fraktiot": "Facciones y configuración inicial",
  "p.4.1": "La partida tiene cuatro facciones situadas en las esquinas del tablero: los rus en la esquina superior izquierda, los mongoles en la superior derecha, Song en la inferior derecha y Khwarezm en la inferior izquierda. El centro del mapa es neutral.",
  "p.4.2": "Cada facción comienza con 12 provincias, una capital y un ejército fundador liderado por el Jefe Tribal (Capítulo XIII). Los recursos iniciales y las bonificaciones especiales se enumeran a continuación.",
  "t1.h.0": "Facción",
  "t1.h.1": "Color",
  "t1.h.2": "Gobernante",
  "t1.h.3": "Capital",
  "t1.h.4": "Oro",
  "t1.h.5": "Efectivos",
  "t1.h.6": "Caballos",
  "t1.h.7": "Bonificaciones especiales",
  "t1.r.0.0": "Imperio mongol",
  "t1.r.0.1": "🟡 amarillo",
  "t1.r.0.2": "Gengis Kan",
  "t1.r.0.3": "Karakorum",
  "t1.r.0.7": "Caballería +30%, asedio +20% · agresivo",
  "t1.r.1.0": "Dinastía Song",
  "t1.r.1.1": "🟢 verde",
  "t1.r.1.2": "Emperador Ningzong",
  "t1.r.1.3": "Lin'an (Hangzhou)",
  "t1.r.1.7": "Impuestos +30%, caballería −10%, asedio −10% · mercantil",
  "t1.r.2.0": "Principados rus",
  "t1.r.2.1": "⚪ gris",
  "t1.r.2.2": "Gran príncipe",
  "t1.r.2.3": "Nóvgorod",
  "t1.r.2.7": "Impuestos +10%, asedio +10% · defensivo",
  "t1.r.3.0": "Imperio de Khwarezm",
  "t1.r.3.1": "🟣 púrpura",
  "t1.r.3.2": "Sha Muhammad II",
  "t1.r.3.3": "Samarcanda",
  "t1.r.3.7": "Caballería +10%, impuestos +20%, asedio +10% · expansionista",
  "p.4.3": "Relaciones iniciales: todas las facciones empiezan neutrales entre sí (relación 0, confianza 50, amenaza 30). Excepción: las demás empiezan con una desconfianza inherente hacia los mongoles (relación −20, amenaza 60), ya que los mongoles son una potencia expansionista agresiva.",
  "p.4.4": "Reservas iniciales (compartidas por todos los jugadores): 10 de comida, 3 artesanos, 0 influencia, 0 prestigio. Mano inicial: 5 cartas (Capítulo XIV).",
  "ch.kartta": "Mapa, provincias y terreno",
  "p.5.1": "El mapa es una cuadrícula hexagonal en la que cada hexágono completo contiene una aldea. Las aldeas se reparten entre las facciones (bordes/esquinas) y los neutrales (centro). La adyacencia se calcula con una disposición hexagonal odd-r: cada casilla limita como máximo con seis vecinas.",
  "p.5.2": "El terreno afecta al coste de movimiento, la defensa, el límite de suministro y los impuestos. El coste de movimiento depende del tipo de unidad (infantería/caballería/asedio). La bonificación de defensa se añade al poder de combate del defensor (Capítulo XI).",
  "t2.h.0": "Terreno",
  "t2.h.1": "Infantería",
  "t2.h.2": "Caballería",
  "t2.h.3": "Asedio",
  "t2.h.4": "Defensa",
  "t2.h.5": "Suministro",
  "t2.h.6": "Multiplicador fiscal",
  "t2.r.0.0": "🌾 Estepa",
  "t2.r.1.0": "🌿 Pradera",
  "t2.r.2.0": "🌾 Tierras de cultivo",
  "t2.r.3.0": "🌲 Bosque",
  "t2.r.4.0": "⛰️ Colinas",
  "t2.r.5.0": "⛰️ Montañas",
  "t2.r.6.0": "🏜️ Desierto",
  "t2.r.7.0": "🌿 Pantano",
  "t2.r.8.0": "🌲 Taiga",
  "t2.r.9.0": "❄️ Tundra",
  "p.5.3": "Las tierras de cultivo y las praderas producen comida; la estepa y las provincias de caballos producen caballos; las tierras de cultivo y las colinas producen artesanos (Capítulo VII). Las montañas y las colinas ofrecen la mejor defensa, pero ralentizan el movimiento.",
  "ch.vuoro": "Estructura del turno (5 fases)",
  "p.6.1": "Cada turno (año) pasa por cinco fases en un orden fijo. Pasa de una fase a la siguiente con el botón \"Siguiente\".",
  "p.6.2": "**1. Recursos:** recoge ingresos de las provincias controladas (oro, efectivos, comida, caballos, artesanos), además de influencia y prestigio. Los ingresos se calculan con las fórmulas del Capítulo VII.",
  "p.6.3": "**2. Cartas:** roba 1 carta del mazo (la mano inicial es de 5) y juega las cartas que quieras de tu mano. Los efectos de las cartas se detallan en el Capítulo XIV.",
  "p.6.4": "**3. Ataque:** mueve ejércitos a provincias vecinas o resuelve ataques contra provincias controladas por enemigos o neutrales (Capítulo XI).",
  "p.6.5": "**4. Construcción:** levanta edificios en tus propias provincias y recluta tropas (Capítulos IX–X).",
  "p.6.6": "**5. Fin de turno:** los oponentes controlados por la IA hacen sus movimientos, los asedios avanzan, las bonificaciones permanentes se actualizan, se comprueban las condiciones de victoria y comienza un nuevo año.",
  "ch.talous": "Recursos y economía",
  "p.7.1": "**Ingresos de oro** = (impuesto base de las provincias + bonificación de la Ruta de la Seda + bonificación de mercado + bonificación de puente) × multiplicador de la capital. Un mercado produce +3 de oro cada uno, un puente de la Ruta de la Seda +2 de oro cada uno. Si se pierde la capital, el multiplicador es 0.5 (ingresos a la mitad); en caso contrario, 1.0.",
  "p.7.2": "**Impulso del inicio de partida:** en los turnos 1–4, se añaden +4 a los ingresos de oro para acelerar la construcción temprana.",
  "p.7.3": "**Efectivos** = 30% de los efectivos base combinados de las provincias (redondeado hacia abajo).",
  "p.7.4": "**Comida** = −1 por ejército (mantenimiento) + 0.5 × provincias de cultivo/pradera + 2 × campamentos. La comida puede ser un cambio negativo; se consume en el mantenimiento de las tropas.",
  "p.7.5": "**Caballos** = número de provincias de estepa/caballos + número de establos (1 por establo).",
  "p.7.6": "**Artesanos** = 0.5 × (provincias de cultivo y colinas) + número de talleres. Si controlas al menos 3 provincias, recibes como mínimo 1 artesano por turno.",
  "p.7.7": "**Influencia/turno** = nodos comerciales (1 cada uno) + capital conservada (2) + alianzas (2 cada una) + Maravillas (2 cada una).",
  "p.7.8": "**Prestigio/turno** = 3 × número de Maravillas.",
  "ch.silkkitie": "La Ruta de la Seda y los nodos comerciales",
  "p.8.1": "La Ruta de la Seda es una ruta comercial que recorre la fila central del mapa. Las provincias situadas a lo largo de ella son nodos comerciales (marcados con una bandera de la Ruta de la Seda).",
  "p.8.2": "**Bonificación de la Ruta de la Seda** = impuesto base de los nodos comerciales + 2 × nodos que producen el bien comercial seda + **bonificación de cadena**. La bonificación de cadena recompensa el control de tramos ininterrumpidos de nodos: cada grupo conectado (tamaño > 1) otorga aproximadamente 1.6 × (tamaño del grupo^1.45) de oro extra. Por ello, un único tramo ininterrumpido de la Ruta de la Seda vale mucho más que paradas dispersas.",
  "p.8.3": "Mantener una mayoría de la Ruta de la Seda (más de la mitad de todos los nodos) es un requisito para la Victoria Económica (§ 3.3) y genera una influencia considerable (§ 7.7).",
  "ch.rakennukset": "Edificios",
  "p.9.1": "Los edificios se construyen durante la fase de Construcción en tus propias provincias. Cuestan oro y a menudo artesanos. Cada edificio otorga un beneficio permanente.",
  "t3.h.0": "Edificio",
  "t3.h.1": "Oro",
  "t3.h.2": "Artesanos",
  "t3.h.3": "Efecto",
  "t3.r.0.0": "⛺ Campamento",
  "t3.r.0.3": "+2 comida/turno; punto de reclutamiento de infantería",
  "t3.r.1.0": "🏪 Mercado",
  "t3.r.1.3": "+3 oro/turno",
  "t3.r.2.0": "🌉 Puente",
  "t3.r.2.3": "+2 oro/turno en la Ruta de la Seda; paso de caravanas",
  "t3.r.3.0": "🔨 Taller",
  "t3.r.3.3": "+1 artesano/turno; las tropas reclutadas obtienen +10 de moral",
  "t3.r.4.0": "🐎 Establo",
  "t3.r.4.3": "+1 caballo/turno; punto de reclutamiento de caballería",
  "t3.r.5.0": "🏯 Fortaleza",
  "t3.r.5.3": "+3 defensa (aumenta el nivel de fortificación)",
  "t3.r.6.0": "🏛️ Maravilla",
  "t3.r.6.3": "Solo en la capital: +prestigio y +influencia/turno",
  "p.9.2": "**Papel de los edificios en el reclutamiento:** un Campamento desbloquea el reclutamiento de infantería y un Establo desbloquea el de caballería. En la capital se pueden reclutar ambas sin un edificio específico (Capítulo X).",
  "p.9.3": "**Maravilla** es la única fuente de prestigio y, por tanto, la clave de la Victoria Cultural. Solo puede construirse en la capital.",
  "ch.armeijat": "Ejércitos, reclutamiento y movimiento",
  "p.10.1": "**Costes de reclutamiento:** la infantería cuesta **10 de oro y 5 de comida**. La caballería cuesta **20 de oro, 5 caballos y 10 de comida**.",
  "p.10.2": "**Requisitos de reclutamiento:** la infantería puede reclutarse desde una provincia con un Campamento (o la capital); la caballería, desde una provincia con un Establo (o la capital). Si se pierde la capital, el reclutamiento queda suspendido hasta recuperarla.",
  "p.10.3": "**Composición del grupo:** un reclutamiento de infantería produce 5 de infantería (+ hasta 2 de caballería según los caballos disponibles). Un reclutamiento de caballería produce caballería igual a min(4 + establos, caballos/2), y el resto como infantería (al menos 2). Un Taller otorga a las tropas nuevas +10 de moral (moral base 70, 80 con un Taller).",
  "p.10.4": "**Movimiento:** un ejército entra en una provincia vecina pagando el coste de movimiento del terreno (Capítulo V). Las unidades de asedio usan el coste de asedio; en caso contrario, un grupo con predominio de caballería (caballería ≥ infantería) usa el coste de caballería, y los grupos con predominio de infantería usan el coste de infantería.",
  "p.10.5": "**Moral y suministro:** cada ejército tiene moral (0–100) y suministro. Una batalla victoriosa eleva la moral (+5). La proximidad del Jefe Tribal eleva la moral (Capítulo XIII).",
  "ch.taistelu": "Sistema de combate",
  "p.11.1": "**Poder de combate:** poder del atacante = 2 × caballería + infantería + asedio + bonificaciones de ataque. Poder del defensor = 2 × caballería + infantería. La caballería vale, por tanto, el doble en poder bruto.",
  "p.11.2": "**Tirada de dado:** ambos bandos tiran 1d6. Puntuación del atacante = poder + dado. Puntuación del defensor = poder + dado + 2 × bonificación de defensa del terreno + 3 × nivel de fortificación efectivo.",
  "p.11.3": "**El asedio debilita los muros:** nivel de fortificación efectivo = nivel de fortificación − 0.5 × unidades de asedio (no por debajo de 0). Las unidades de asedio erosionan así la defensa.",
  "p.11.4": "**Resolución:** quien obtenga la puntuación más alta gana. Si gana el atacante, el defensor sufre daño (poder del atacante − bonificaciones de defensa); si pierde el atacante, el atacante sufre daño igual al poder del defensor.",
  "p.11.5": "**Asignación de bajas:** el daño golpea primero a la infantería; cualquier daño restante elimina caballería con la mitad de eficacia (la caballería resiste mejor). El defensor es destruido si pierde toda su caballería y su infantería.",
  "p.11.6": "**Efectos de cartas:** las cartas de estrategia jugadas pueden otorgar bonificaciones de ataque, defensa o movimiento, que se añaden al cálculo de poder (Capítulo XIV).",
  "ch.piiritys": "Asedio y capitales",
  "p.12.1": "**Bloqueo:** si una provincia está completamente rodeada por vecinos controlados por el enemigo, queda sitiada y el medidor de asedio aumenta turno a turno.",
  "p.12.2": "**Efecto del asedio:** si la provincia tiene una fortaleza, su nivel disminuye en −1/turno bajo asedio. Si no hay fortaleza, el propietario pierde 5 de oro/turno (se corta el suministro). El medidor de asedio se reinicia una vez que se levanta el bloqueo.",
  "p.12.3": "**Capital perdida:** si tu propia capital está en manos del enemigo, (a) todos los ingresos de oro se reducen a la mitad (§ 7.1) y (b) el reclutamiento queda suspendido (§ 10.2) hasta recuperar la capital.",
  "p.12.4": "**Las capitales enemigas** son la clave de la Victoria Militar: capturar cada capital enemiga termina la partida en victoria (§ 3.2).",
  "ch.paallikko": "Jefe Tribal",
  "p.13.1": "El ejército fundador de cada facción (el ejército \"principal\") lleva consigo al Jefe Tribal. El Jefe es a la vez líder y fuente de moral.",
  "p.13.2": "**Bonificación de moral:** los ejércitos en la misma provincia que el Jefe obtienen +5 de moral, y los ejércitos en provincias vecinas reciben una bonificación menor. Las bonificaciones se actualizan al final del turno.",
  "p.13.3": "**Muerte del Jefe:** si el ejército fundador del jugador es destruido, sigue una penalización única: **−30 de oro**, **−15 de influencia**, y la moral de todas las tropas del jugador cae (−10). Esto sucede solo una vez.",
  "p.13.4": "Proteger al Jefe es, por tanto, estratégicamente importante: no envíes al ejército fundador a correr riesgos innecesarios al principio.",
  "ch.kortit": "Sistema de cartas",
  "p.14.1": "**Robo de cartas:** la partida comienza con una mano de 5 cartas; durante la fase de Cartas robas 1 carta nueva por turno. Las cartas jugadas van a la pila de descarte (excepto las cartas de tecnología permanentes).",
  "p.14.2": "**Tipos de carta:** estrategia (bonificaciones de combate), tecnología (bonificaciones permanentes; 5 jugadas = Victoria Tecnológica), diplomacia (relaciones) y recursos (oro/comida/caballos/artesanos).",
  "p.14.3": "**Rarezas:** común, poco común, rara, legendaria. Las cartas más raras son más poderosas, pero aparecen con menor frecuencia.",
  "p.14.4": "**Duración de los efectos:** las cartas de recursos surten efecto de inmediato (oro/comida/caballos/artesanos se añaden a las reservas). Las bonificaciones de ataque/defensa duran una duración determinada (a menudo solo este turno); una bonificación de movimiento añade puntos de movimiento inmediatamente. Las cartas permanentes de ataque/defensa (tecnología) permanecen en efecto durante el resto de la partida.",
  "p.14.5": "Las cartas aparecen ilustradas en el panel de cartas de la parte inferior de la vista de juego. El panel puede agrandarse o reducirse arrastrando su borde superior; las cartas siempre se ajustan para seguir siendo totalmente visibles.",
  "ch.diplomatia": "Diplomacia",
  "p.15.1": "**Relaciones:** cada par de facciones tiene un valor de relación, confianza, amenaza y fricción fronteriza. Los tratados cambian estos valores.",
  "p.15.2": "**Tipos de tratado:** pacíficos — no agresión, paz, tregua y alianza; y relacionados con la guerra — guerra formal (war_formal) y ataque sorpresa (war_surprise).",
  "p.15.3": "**Alianza** genera +2 influencia/turno (§ 7.7). Una alianza con cada enemigo superviviente (al menos 2) es una vía hacia la Victoria Diplomática (§ 3.5).",
  "p.15.4": "**Declaración de guerra:** una guerra formal se activa en un turno fijado y derrumba las relaciones (−90) y la confianza (0), y aumenta la amenaza (+30). Los mongoles ya cargan con una amenaza inicial más alta desde el principio (§ 4.3).",
  "ch.kauppa": "Bienes comerciales",
  "p.16.1": "Algunas provincias producen un bien comercial, que otorga un beneficio permanente a su propietario. El valor describe la valía relativa del bien en el comercio.",
  "t4.h.0": "Bien",
  "t4.h.1": "Valor",
  "t4.h.2": "Efecto",
  "t4.r.0.0": "🪙 Oro",
  "t4.r.0.2": "+3 oro/turno",
  "t4.r.1.0": "🧣 Seda",
  "t4.r.1.2": "+3 oro/turno (refuerza la Ruta de la Seda)",
  "t4.r.2.0": "💎 Gemas",
  "t4.r.2.2": "+2 oro/turno y +1 moral",
  "t4.r.3.0": "🌶️ Especias",
  "t4.r.3.2": "+2 oro/turno",
  "t4.r.4.0": "🧥 Pieles",
  "t4.r.4.2": "+1 suministro y +1 moral",
  "t4.r.5.0": "🐴 Caballos",
  "t4.r.5.2": "+2 al reclutamiento de caballería",
  "t4.r.6.0": "⚔️ Hierro",
  "t4.r.6.2": "−20% coste de unidades",
  "t4.r.7.0": "🧂 Sal",
  "t4.r.7.2": "+1 suministro",
  "t4.r.8.0": "🌾 Grano",
  "t4.r.8.2": "+2 efectivos",
  "t4.r.9.0": "🐄 Ganado",
  "t4.r.9.2": "+1 efectivos, +1 suministro",
  "ch.tekoaly": "Inteligencia artificial (IA)",
  "p.17.1": "Al final de un turno, cada facción controlada por la IA actúa según su personalidad: la agresiva (mongoles) se expande y ataca, la mercantil (Song) se centra en la economía, la defensiva (rus) se fortifica y la expansionista (Khwarezm) toma provincias neutrales.",
  "p.17.2": "La IA puede ganar por victoria militar o económica en las mismas condiciones que el jugador. Los movimientos de la IA se muestran en las notificaciones de fin de turno.",
  "p.17.3": "La IA tiene en cuenta los valores de amenaza y relación: una amenaza alta aumenta la probabilidad de ataque. La alta amenaza inicial de los mongoles los convierte en un agresor probable.",
  "ch.strategia": "Consejos estratégicos",
  "p.18.1": "**Usa el impulso del inicio de partida:** en los turnos 1–4 obtienes +4 oro/turno. Construye mercados y campamentos pronto como base de tu economía y tu reclutamiento.",
  "p.18.2": "**Mantén la Ruta de la Seda en un solo tramo ininterrumpido:** la bonificación de cadena (§ 8.2) recompensa de forma desproporcionada los nodos comerciales adyacentes — reúne un tramo continuo en lugar de paradas dispersas.",
  "p.18.3": "**Protege tu capital y a tu Jefe:** una capital perdida reduce a la mitad los ingresos y detiene el reclutamiento; la muerte del Jefe cuesta 30 de oro y 15 de influencia.",
  "p.18.4": "**Elige pronto tu vía de victoria:** para los mongoles, la vía militar es la natural (caballería +30%); para Song, la económica y la cultural (impuestos +30%); para Khwarezm, la expansión; y para los rus, una guerra defensiva de desgaste.",
  "p.18.5": "**Aprovecha el terreno:** defiende en montañas y colinas (+3/+2 defensa), ataca con caballería en terreno abierto, donde el movimiento es barato.",
  "p.18.6": "**Unidades de asedio contra murallas:** lleva unidades de asedio contra provincias fortificadas — debilitan el nivel de fortificación efectivo (§ 11.3)."
};

export default translations;
