// Sääntökirjan käännös (fr). Avaimet vastaavat Ohjekirja.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.chapter": "Chapitre",
  "ui.title": "Tales of the Steppe — Livre de règles",
  "ui.subtitle": "Histoire de la steppe · année 1206 · article par article",
  "ui.print": "Imprimer",
  "ui.toGame": "Au jeu",
  "ui.search": "Rechercher des chapitres…",
  "ui.footer": "Tales of the Steppe — Histoire de la steppe · Livre de règles · année 1206",
  "ui.backToTop": "↑ Retour en haut",
  "ui.returnToGame": "Retour au jeu",
  "ch.johdanto": "Introduction et concept du jeu",
  "p.1.1": "Tales of the Steppe (Histoire de la steppe) est un jeu de stratégie au tour par tour se déroulant en 1206 apr. J.-C. — le moment où Temüjin fut proclamé Gengis Khan et où les peuples de la steppe bouleversèrent le monde. Le joueur dirige l'une des quatre grandes puissances et cherche la victoire par l'une des cinq voies différentes (Chapitre III).",
  "p.1.2": "C'est un jeu solo contre des adversaires IA. Chaque année correspond à un tour, divisé en cinq phases (Chapitre VI). Le joueur contrôle des provinces (villages), collecte des ressources, construit des bâtiments, recrute des armées, joue des cartes et mène diplomatie et guerre.",
  "p.1.3": "Ce livre de règles décrit les règles du jeu exactement telles qu'elles sont implémentées. Les valeurs numériques (coûts, bonus, seuils) font foi et correspondent à la logique du jeu. En cas de conflit, le jeu lui-même fait autorité, mais l'objectif est que ce livre et le jeu concordent.",
  "ch.kasitteet": "Concepts de base et terminologie",
  "p.2.1": "**Province (village) :** une case hexagonale sur la carte. Chaque province a un propriétaire (une faction ou un neutre), un terrain, un développement de base, une éventuelle marchandise commerciale et un niveau de fortification.",
  "p.2.2": "**Faction :** un royaume jouable. Quatre factions sont disponibles : les Mongols, Song (Chine), les principautés russes et le Khwarezm (Perse).",
  "p.2.3": "**Ressources :** or, nourriture, chevaux, main-d’œuvre et artisans. S'y ajoutent deux jauges proches du prestige : influence et prestige.",
  "p.2.4": "**Influence :** poids diplomatique, généré par les nœuds commerciaux, la possession de votre capitale, les alliances et les Merveilles. La jauge de Victoire diplomatique.",
  "p.2.5": "**Prestige :** renommée culturelle, générée uniquement par les Merveilles (un bâtiment). La jauge de Victoire culturelle.",
  "p.2.6": "**Armée :** une pile d'unités composée de cavalerie, d'infanterie et éventuellement d'unités de siège, avec en plus un moral et un ravitaillement.",
  "p.2.7": "**Route de la soie :** une route commerciale traversant la carte ; les provinces qui la longent sont des nœuds commerciaux qui génèrent un revenu supplémentaire et de l'influence (Chapitre VIII).",
  "ch.voitto": "Conditions de victoire — cinq voies",
  "p.3.1": "La partie se termine par une victoire lorsque l'une des cinq conditions suivantes est remplie à la fin du tour d'un joueur. Les conditions sont vérifiées à la fin de chaque tour.",
  "p.3.2": "**Victoire militaire :** capturez la capitale de chaque faction ennemie — OU contrôlez au moins **30 provinces** (environ 40% de la carte).",
  "p.3.3": "**Victoire économique :** trois conditions en même temps : (a) au moins **500 or** dans le trésor, (b) vous contrôlez une **majorité des nœuds commerciaux de la Route de la soie** (plus de la moitié), et (c) vous maintenez le seuil d'or pendant **au moins 3 tours consécutifs** (la série se réinitialise si l'or descend sous 500).",
  "p.3.4": "**Victoire technologique :** jouez **au moins 5 cartes de technologie** (cartes technologiques permanentes).",
  "p.3.5": "**Victoire diplomatique :** atteignez **au moins 100 influence** — OU formez une alliance avec chaque faction ennemie survivante (au moins 2 alliés).",
  "p.3.6": "**Victoire culturelle :** accumulez **au moins 60 prestige** en construisant des Merveilles dans votre capitale.",
  "p.3.7": "**Défaite :** le joueur perd s'il perd toutes ses provinces et toutes ses armées. L'IA peut aussi gagner par victoire militaire ou économique, ce qui met fin à la partie.",
  "ch.fraktiot": "Factions et configuration initiale",
  "p.4.1": "Le jeu comporte quatre factions placées dans les coins du plateau : les Rus en haut à gauche, les Mongols en haut à droite, Song en bas à droite et le Khwarezm en bas à gauche. Le centre de la carte est neutre.",
  "p.4.2": "Chaque faction commence avec 12 provinces, une capitale et une armée fondatrice dirigée par le Chef tribal (Chapitre XIII). Les ressources de départ et les bonus spéciaux sont listés ci-dessous.",
  "t1.h.0": "Faction",
  "t1.h.1": "Couleur",
  "t1.h.2": "Souverain",
  "t1.h.3": "Capitale",
  "t1.h.4": "Or",
  "t1.h.5": "Main-d’œuvre",
  "t1.h.6": "Chevaux",
  "t1.h.7": "Bonus spéciaux",
  "t1.r.0.0": "Empire mongol",
  "t1.r.0.1": "🟡 jaune",
  "t1.r.0.2": "Gengis Khan",
  "t1.r.0.3": "Karakorum",
  "t1.r.0.7": "Cavalerie +30%, siège +20% · agressif",
  "t1.r.1.0": "Dynastie Song",
  "t1.r.1.1": "🟢 vert",
  "t1.r.1.2": "Empereur Ningzong",
  "t1.r.1.3": "Lin'an (Hangzhou)",
  "t1.r.1.7": "Fiscalité +30%, cavalerie −10%, siège −10% · marchand",
  "t1.r.2.0": "Principautés russes",
  "t1.r.2.1": "⚪ gris",
  "t1.r.2.2": "Grand-prince",
  "t1.r.2.3": "Novgorod",
  "t1.r.2.7": "Fiscalité +10%, siège +10% · défensif",
  "t1.r.3.0": "Empire khwarezmien",
  "t1.r.3.1": "🟣 violet",
  "t1.r.3.2": "Shah Muhammad II",
  "t1.r.3.3": "Samarcande",
  "t1.r.3.7": "Cavalerie +10%, fiscalité +20%, siège +10% · expansionniste",
  "p.4.3": "Relations de départ : toutes les factions commencent neutres les unes envers les autres (relation 0, confiance 50, menace 30). Exception : les autres commencent avec une suspicion inhérente envers les Mongols (relation −20, menace 60), car les Mongols sont une puissance agressive et expansionniste.",
  "p.4.4": "Réserve de départ (commune à tous les joueurs) : 10 nourriture, 3 artisans, 0 influence, 0 prestige. Main de départ : 5 cartes (Chapitre XIV).",
  "ch.kartta": "Carte, provinces et terrain",
  "p.5.1": "La carte est une grille hexagonale où chaque hexagone complet contient un village. Les villages sont répartis entre les factions (bords/coins) et les neutres (centre). L'adjacence est calculée selon une disposition hexagonale odd-r : chaque case touche au plus six voisines.",
  "p.5.2": "Le terrain affecte le coût de déplacement, la défense, la limite de ravitaillement et la fiscalité. Le coût de déplacement dépend du type d'unité (infanterie/cavalerie/siège). Le bonus de défense est ajouté à la puissance de combat du défenseur (Chapitre XI).",
  "t2.h.0": "Terrain",
  "t2.h.1": "Infanterie",
  "t2.h.2": "Cavalerie",
  "t2.h.3": "Siège",
  "t2.h.4": "Défense",
  "t2.h.5": "Ravitaillement",
  "t2.h.6": "Multiplicateur fiscal",
  "t2.r.0.0": "🌾 Steppe",
  "t2.r.1.0": "🌿 Prairie",
  "t2.r.2.0": "🌾 Terres agricoles",
  "t2.r.3.0": "🌲 Forêt",
  "t2.r.4.0": "⛰️ Collines",
  "t2.r.5.0": "⛰️ Montagnes",
  "t2.r.6.0": "🏜️ Désert",
  "t2.r.7.0": "🌿 Marais",
  "t2.r.8.0": "🌲 Taïga",
  "t2.r.9.0": "❄️ Toundra",
  "p.5.3": "Les terres agricoles et les prairies produisent de la nourriture ; les provinces de steppe et de chevaux produisent des chevaux ; les terres agricoles et les collines produisent des artisans (Chapitre VII). Les montagnes et les collines offrent la meilleure défense, mais ralentissent le déplacement.",
  "ch.vuoro": "Structure du tour (5 phases)",
  "p.6.1": "Chaque tour (année) se déroule en cinq phases dans un ordre fixe. Passez d'une phase à l'autre avec le bouton « Suivant ».",
  "p.6.2": "**1. Ressources :** collectez les revenus des provinces contrôlées (or, main-d’œuvre, nourriture, chevaux, artisans) ainsi que l'influence et le prestige. Les revenus sont calculés avec les formules du Chapitre VII.",
  "p.6.3": "**2. Cartes :** piochez 1 carte du paquet (la main de départ est de 5) et jouez les cartes de votre main que vous souhaitez. Les effets des cartes sont décrits au Chapitre XIV.",
  "p.6.4": "**3. Attaque :** déplacez des armées vers des provinces voisines ou résolvez des attaques contre des provinces contrôlées par l'ennemi ou des neutres (Chapitre XI).",
  "p.6.5": "**4. Construction :** construisez des bâtiments dans vos propres provinces et recrutez des troupes (Chapitres IX–X).",
  "p.6.6": "**5. Fin du tour :** les adversaires IA jouent leurs actions, les sièges progressent, les bonus permanents se mettent à jour, les conditions de victoire sont vérifiées et une nouvelle année commence.",
  "ch.talous": "Ressources et économie",
  "p.7.1": "**Revenu en or** = (taxe de base des provinces + bonus de la Route de la soie + bonus de marché + bonus de pont) × multiplicateur de capitale. Un marché rapporte +3 or chacun, un pont sur la Route de la soie +2 or chacun. Si la capitale est perdue, le multiplicateur est de 0.5 (revenu divisé par deux), sinon 1.0.",
  "p.7.2": "**Coup de pouce de début de partie :** aux tours 1–4, +4 est ajouté au revenu en or pour accélérer les premières constructions.",
  "p.7.3": "**Main-d’œuvre** = 30% de la main-d’œuvre de base combinée des provinces (arrondi à l'inférieur).",
  "p.7.4": "**Nourriture** = −1 par armée (entretien) + 0.5 × provinces de terres agricoles/prairies + 2 × camps. La nourriture peut être une variation négative ; elle est consommée par l'entretien des troupes.",
  "p.7.5": "**Chevaux** = nombre de provinces de steppe/à chevaux + nombre d'écuries (1 par écurie).",
  "p.7.6": "**Artisans** = 0.5 × (provinces de terres agricoles et de collines) + nombre d'ateliers. Si vous contrôlez au moins 3 provinces, vous obtenez au moins 1 artisan par tour.",
  "p.7.7": "**Influence/tour** = nœuds commerciaux (1 chacun) + capitale tenue (2) + alliances (2 chacune) + Merveilles (2 chacune).",
  "p.7.8": "**Prestige/tour** = 3 × nombre de Merveilles.",
  "ch.silkkitie": "La Route de la soie et les nœuds commerciaux",
  "p.8.1": "La Route de la soie est une route commerciale traversant la rangée centrale de la carte. Les provinces qui la bordent sont des nœuds commerciaux (marqués d'un drapeau de la Route de la soie).",
  "p.8.2": "**Bonus de la Route de la soie** = taxe de base des nœuds commerciaux + 2 × nœuds produisant la marchandise de soie + **bonus de chaîne**. Le bonus de chaîne récompense le contrôle de séries ininterrompues de nœuds : chaque groupe connecté (taille > 1) accorde environ 1.6 × (taille du groupe^1.45) or supplémentaire. Une seule portion continue de la Route de la soie a donc bien plus de valeur que des étapes dispersées.",
  "p.8.3": "Détenir une majorité de la Route de la soie (plus de la moitié de tous les nœuds) est une condition de la Victoire économique (§ 3.3) et génère une influence significative (§ 7.7).",
  "ch.rakennukset": "Bâtiments",
  "p.9.1": "Les bâtiments sont construits pendant la phase Construction dans vos propres provinces. Ils coûtent de l'or et souvent des artisans. Chaque bâtiment accorde un avantage permanent.",
  "t3.h.0": "Bâtiment",
  "t3.h.1": "Or",
  "t3.h.2": "Artisans",
  "t3.h.3": "Effet",
  "t3.r.0.0": "⛺ Camp",
  "t3.r.0.3": "+2 nourriture/tour ; point de recrutement d'infanterie",
  "t3.r.1.0": "🏪 Marché",
  "t3.r.1.3": "+3 or/tour",
  "t3.r.2.0": "🌉 Pont",
  "t3.r.2.3": "+2 or/tour sur la Route de la soie ; point de passage des caravanes",
  "t3.r.3.0": "🔨 Atelier",
  "t3.r.3.3": "+1 artisan/tour ; les troupes recrutées gagnent +10 de moral",
  "t3.r.4.0": "🐎 Écurie",
  "t3.r.4.3": "+1 cheval/tour ; point de recrutement de cavalerie",
  "t3.r.5.0": "🏯 Forteresse",
  "t3.r.5.3": "+3 défense (augmente le niveau de fortification)",
  "t3.r.6.0": "🏛️ Merveille",
  "t3.r.6.3": "Capitale uniquement : +prestige et +influence/tour",
  "p.9.2": "**Rôle des bâtiments dans le recrutement :** un Camp débloque le recrutement d'infanterie, une Écurie débloque le recrutement de cavalerie. Dans la capitale, les deux peuvent être recrutées sans bâtiment dédié (Chapitre X).",
  "p.9.3": "**Merveille** est la seule source de prestige et donc la clé de la Victoire culturelle. Elle ne peut être construite que dans la capitale.",
  "ch.armeijat": "Armées, recrutement et déplacement",
  "p.10.1": "**Coûts de recrutement :** l'infanterie coûte **10 or et 5 nourriture**. La cavalerie coûte **20 or, 5 chevaux et 10 nourriture**.",
  "p.10.2": "**Conditions de recrutement :** l'infanterie peut être recrutée depuis une province avec un Camp (ou la capitale) ; la cavalerie depuis une province avec une Écurie (ou la capitale). Si la capitale est perdue, le recrutement est suspendu jusqu'à sa reprise.",
  "p.10.3": "**Composition de la pile :** un recrutement d'infanterie produit 5 fantassins (+ jusqu'à 2 cavaliers selon les chevaux disponibles). Un recrutement de cavalerie produit une cavalerie égale à min(4 + écuries, chevaux/2), le reste en infanterie (au moins 2). Un Atelier accorde +10 de moral aux nouvelles troupes (moral de base 70, 80 avec un Atelier).",
  "p.10.4": "**Déplacement :** une armée se déplace vers une province voisine en payant le coût de déplacement du terrain (Chapitre V). Les unités de siège utilisent le coût de siège ; sinon, une pile à dominante cavalerie (cavalerie ≥ infanterie) utilise le coût de cavalerie, et les piles à dominante infanterie utilisent le coût d'infanterie.",
  "p.10.5": "**Moral et ravitaillement :** chaque armée a un moral (0–100) et un ravitaillement. Une bataille victorieuse augmente le moral (+5). La proximité du Chef tribal augmente le moral (Chapitre XIII).",
  "ch.taistelu": "Système de combat",
  "p.11.1": "**Puissance de combat :** Puissance de l'attaquant = 2 × cavalerie + infanterie + siège + bonus d'attaque. Puissance du défenseur = 2 × cavalerie + infanterie. La cavalerie vaut donc le double en puissance brute.",
  "p.11.2": "**Jet de dé :** les deux camps lancent 1d6. Score de l'attaquant = puissance + dé. Score du défenseur = puissance + dé + 2 × bonus de défense du terrain + 3 × niveau de fortification effectif.",
  "p.11.3": "**Le siège affaiblit les murs :** niveau de fortification effectif = niveau de fortification − 0.5 × unités de siège (pas en dessous de 0). Les unités de siège érodent donc la défense.",
  "p.11.4": "**Résolution :** le camp qui obtient le score le plus élevé gagne. Si l'attaquant gagne, le défenseur subit des dégâts (puissance de l'attaquant − bonus de défense) ; si l'attaquant perd, l'attaquant subit des dégâts égaux à la puissance du défenseur.",
  "p.11.5": "**Répartition des pertes :** les dégâts touchent d'abord l'infanterie ; tout dégât restant élimine la cavalerie à demi-efficacité (la cavalerie est plus résistante). Le défenseur est détruit s'il perd toute sa cavalerie et toute son infanterie.",
  "p.11.6": "**Effets des cartes :** les cartes de stratégie jouées peuvent accorder des bonus d'attaque, de défense ou de déplacement, qui s'ajoutent au calcul de puissance (Chapitre XIV).",
  "ch.piiritys": "Siège et capitales",
  "p.12.1": "**Blocus :** si une province est complètement entourée de voisins contrôlés par l'ennemi, elle devient assiégée et la jauge de siège augmente tour après tour.",
  "p.12.2": "**Effet du siège :** si la province possède une forteresse, son niveau baisse de −1/tour sous siège. S'il n'y a pas de forteresse, le propriétaire perd 5 or/tour (le ravitaillement est coupé). La jauge de siège se réinitialise une fois le blocus levé.",
  "p.12.3": "**Capitale perdue :** si votre propre capitale est aux mains de l'ennemi, (a) tout revenu en or est divisé par deux (§ 7.1) et (b) le recrutement est suspendu (§ 10.2) jusqu'à la reprise de la capitale.",
  "p.12.4": "**Les capitales ennemies** sont la clé de la Victoire militaire : capturer chaque capitale ennemie met fin à la partie par la victoire (§ 3.2).",
  "ch.paallikko": "Chef tribal",
  "p.13.1": "L'armée fondatrice (l'armée « principale ») de chaque faction porte le Chef tribal. Le Chef est à la fois un dirigeant et une source de moral.",
  "p.13.2": "**Bonus de moral :** les armées dans la même province que le Chef gagnent +5 de moral, et les armées des provinces voisines obtiennent un bonus plus faible. Les bonus se mettent à jour à la fin du tour.",
  "p.13.3": "**Mort du Chef :** si l'armée fondatrice du joueur est détruite, une pénalité unique s'applique : **−30 or**, **−15 influence**, et le moral de toutes les troupes du joueur chute (−10). Cela n'arrive qu'une seule fois.",
  "p.13.4": "Protéger le Chef est donc stratégiquement important : n'envoyez pas l'armée fondatrice prendre des risques inutiles en début de partie.",
  "ch.kortit": "Système de cartes",
  "p.14.1": "**Pioche de cartes :** la partie commence avec une main de 5 cartes ; pendant la phase Cartes, vous piochez 1 nouvelle carte par tour. Les cartes jouées vont dans la défausse (sauf les cartes de technologie permanentes).",
  "p.14.2": "**Types de cartes :** stratégie (bonus de combat), technologie (bonus permanents ; 5 jouées = Victoire technologique), diplomatie (relations) et ressource (or/nourriture/chevaux/artisans).",
  "p.14.3": "**Raretés :** commune, peu commune, rare, légendaire. Les cartes plus rares sont plus puissantes mais apparaissent moins souvent.",
  "p.14.4": "**Durée des effets :** les cartes de ressource prennent effet immédiatement (or/nourriture/chevaux/artisans sont ajoutés aux réserves). Les bonus d'attaque/défense durent une durée déterminée (souvent seulement ce tour-ci) ; un bonus de déplacement ajoute immédiatement des points de mouvement. Les cartes permanentes d'attaque/défense (technologie) restent en effet pour le reste de la partie.",
  "p.14.5": "Les cartes apparaissent illustrées dans le panneau de cartes au bas de la vue de jeu. Le panneau peut être agrandi ou réduit en faisant glisser son bord supérieur ; les cartes s'ajustent toujours pour rester entièrement visibles.",
  "ch.diplomatia": "Diplomatie",
  "p.15.1": "**Relations :** chaque paire de factions a un score de relation, une confiance, une menace et une friction frontalière. Les traités modifient ces valeurs.",
  "p.15.2": "**Types de traités :** pacifiques — non-agression, paix, trêve et alliance ; et liés à la guerre — guerre formelle (war_formal) et attaque surprise (war_surprise).",
  "p.15.3": "**Alliance** génère +2 influence/tour (§ 7.7). Une alliance avec chaque ennemi survivant (au moins 2) est l'une des voies vers la Victoire diplomatique (§ 3.5).",
  "p.15.4": "**Déclaration de guerre :** une guerre formelle s'active à un tour fixé et fait chuter les relations (−90) ainsi que la confiance (0), tout en augmentant la menace (+30). Les Mongols portent déjà une menace initiale plus élevée dès le départ (§ 4.3).",
  "ch.kauppa": "Marchandises",
  "p.16.1": "Certaines provinces produisent une marchandise, qui accorde un avantage permanent à son propriétaire. La valeur décrit la valeur relative du bien dans le commerce.",
  "t4.h.0": "Bien",
  "t4.h.1": "Valeur",
  "t4.h.2": "Effet",
  "t4.r.0.0": "🪙 Or",
  "t4.r.0.2": "+3 or/tour",
  "t4.r.1.0": "🧣 Soie",
  "t4.r.1.2": "+3 or/tour (renforce la Route de la soie)",
  "t4.r.2.0": "💎 Gemmes",
  "t4.r.2.2": "+2 or/tour et +1 moral",
  "t4.r.3.0": "🌶️ Épices",
  "t4.r.3.2": "+2 or/tour",
  "t4.r.4.0": "🧥 Fourrures",
  "t4.r.4.2": "+1 ravitaillement et +1 moral",
  "t4.r.5.0": "🐴 Chevaux",
  "t4.r.5.2": "+2 recrutement de cavalerie",
  "t4.r.6.0": "⚔️ Fer",
  "t4.r.6.2": "−20% coût des unités",
  "t4.r.7.0": "🧂 Sel",
  "t4.r.7.2": "+1 ravitaillement",
  "t4.r.8.0": "🌾 Grain",
  "t4.r.8.2": "+2 main-d’œuvre",
  "t4.r.9.0": "🐄 Bétail",
  "t4.r.9.2": "+1 main-d’œuvre, +1 ravitaillement",
  "ch.tekoaly": "Intelligence artificielle (IA)",
  "p.17.1": "À la fin d'un tour, chaque faction IA agit selon sa personnalité : l'agressive (Mongols) s'étend et attaque, la marchande (Song) se concentre sur l'économie, la défensive (Rus) se fortifie, et l'expansionniste (Khwarezm) prend des provinces neutres.",
  "p.17.2": "L'IA peut gagner par victoire militaire ou économique dans les mêmes conditions que le joueur. Les actions de l'IA sont affichées dans les notifications de fin de tour.",
  "p.17.3": "L'IA tient compte des scores de menace et de relation : une menace élevée augmente la probabilité d'attaque. La menace initiale élevée des Mongols en fait un agresseur probable.",
  "ch.strategia": "Conseils stratégiques",
  "p.18.1": "**Utilisez le coup de pouce de début de partie :** aux tours 1–4, vous obtenez +4 or/tour. Construisez tôt des marchés et des camps comme base de votre économie et de votre recrutement.",
  "p.18.2": "**Tenez la Route de la soie d'un seul tenant :** le bonus de chaîne (§ 8.2) récompense de façon disproportionnée les nœuds commerciaux adjacents — construisez une seule ligne ininterrompue plutôt que des arrêts dispersés.",
  "p.18.3": "**Protégez votre capitale et votre Chef :** une capitale perdue divise le revenu par deux et arrête le recrutement ; la mort du Chef coûte 30 or et 15 influence.",
  "p.18.4": "**Choisissez tôt votre voie de victoire :** pour les Mongols, la voie militaire est naturelle (cavalerie +30%), pour Song les voies économique et culturelle (fiscalité +30%), pour le Khwarezm l'expansion, et pour les Rus une guerre défensive d'attrition.",
  "p.18.5": "**Utilisez le terrain :** défendez-vous dans les montagnes et les collines (+3/+2 défense), attaquez avec la cavalerie en terrain ouvert où le déplacement est peu coûteux.",
  "p.18.6": "**Unités de siège contre les murs :** amenez des unités de siège contre les provinces fortifiées — elles affaiblissent le niveau de fortification effectif (§ 11.3)."
};

export default translations;
