// Sääntökirjan käännös (id). Avaimet vastaavat Ohjekirja.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.chapter": "Bab",
  "ui.title": "Tales of the Steppe — Buku Aturan",
  "ui.subtitle": "Kisah Padang Stepa · tahun 1206 · per pasal",
  "ui.print": "Cetak",
  "ui.toGame": "Ke permainan",
  "ui.search": "Cari bab…",
  "ui.footer": "Tales of the Steppe — Kisah Padang Stepa · Buku Aturan · tahun 1206",
  "ui.backToTop": "↑ Kembali ke atas",
  "ui.returnToGame": "Kembali ke permainan",
  "ch.johdanto": "Pendahuluan dan konsep permainan",
  "p.1.1": "Tales of the Steppe (Kisah Padang Stepa) adalah permainan strategi berbasis giliran yang berlatar tahun 1206 M — saat Temüjin diproklamasikan sebagai Genghis Khan dan bangsa-bangsa stepa mengguncang dunia. Pemain memimpin salah satu dari empat kekuatan besar dan berusaha meraih kemenangan melalui salah satu dari lima jalur berbeda (Bab III).",
  "p.1.2": "Ini adalah permainan pemain tunggal melawan lawan AI. Setiap tahun adalah satu giliran, yang dibagi menjadi lima fase (Bab VI). Pemain mengendalikan provinsi (desa), mengumpulkan sumber daya, membangun bangunan, merekrut pasukan, memainkan kartu, dan menjalankan diplomasi serta perang.",
  "p.1.3": "Buku aturan ini menjelaskan aturan permainan persis sebagaimana diterapkan. Nilai numerik (biaya, bonus, ambang) bersifat mengikat dan cocok dengan logika permainan. Jika terjadi pertentangan, permainan itu sendiri adalah otoritas utama, tetapi tujuannya adalah agar buku ini dan permainannya sejalan.",
  "ch.kasitteet": "Konsep dasar dan istilah",
  "p.2.1": "**Provinsi (desa):** satu petak heks di peta. Setiap provinsi memiliki pemilik (sebuah faksi atau netral), medan, perkembangan dasar, kemungkinan barang dagang, dan tingkat fortifikasi.",
  "p.2.2": "**Faksi:** sebuah negeri yang dapat dimainkan. Ada empat faksi yang tersedia: Mongol, Song (Tiongkok), kepangeranan Rus, dan Khwarezm (Persia).",
  "p.2.3": "**Sumber daya:** emas, makanan, kuda, tenaga manusia, dan perajin. Ditambah dua meter mirip prestise: pengaruh dan prestise.",
  "p.2.4": "**Pengaruh:** bobot diplomatik, dihasilkan oleh simpul dagang, mempertahankan ibu kota, aliansi, dan Keajaiban. Meter Kemenangan Diplomatik.",
  "p.2.5": "**Prestise:** kemasyhuran budaya, dihasilkan hanya oleh Keajaiban (sebuah bangunan). Meter Kemenangan Budaya.",
  "p.2.6": "**Pasukan:** satu tumpukan unit dengan kavaleri, infanteri, dan mungkin unit pengepungan, ditambah moral dan suplai.",
  "p.2.7": "**Jalur Sutra:** rute dagang yang membentang melintasi peta; provinsi di sepanjangnya adalah simpul dagang yang menghasilkan pendapatan dan pengaruh tambahan (Bab VIII).",
  "ch.voitto": "Syarat kemenangan — lima jalur",
  "p.3.1": "Permainan berakhir dengan kemenangan ketika salah satu dari lima syarat berikut terpenuhi pada akhir giliran pemain. Syarat-syarat ini diperiksa pada akhir setiap giliran.",
  "p.3.2": "**Kemenangan Militer:** rebut ibu kota setiap faksi musuh — ATAU kuasai setidaknya **30 provinsi** (sekitar 40% peta).",
  "p.3.3": "**Kemenangan Ekonomi:** tiga syarat sekaligus: (a) setidaknya **500 emas** di perbendaharaan, (b) Anda menguasai **mayoritas simpul dagang Jalur Sutra** (lebih dari setengah), dan (c) Anda mempertahankan ambang emas itu selama **setidaknya 3 giliran berturut-turut** (rangkaian direset jika emas turun di bawah 500).",
  "p.3.4": "**Kemenangan Teknologi:** mainkan **setidaknya 5 kartu teknologi** (kartu teknologi permanen).",
  "p.3.5": "**Kemenangan Diplomatik:** capai **setidaknya 100 pengaruh** — ATAU bentuk aliansi dengan setiap faksi musuh yang masih hidup (setidaknya 2 sekutu).",
  "p.3.6": "**Kemenangan Budaya:** kumpulkan **setidaknya 60 prestise** dengan membangun Keajaiban di ibu kota Anda.",
  "p.3.7": "**Kekalahan:** pemain kalah jika kehilangan semua provinsi dan semua pasukannya. AI juga dapat menang melalui kemenangan militer atau ekonomi, yang mengakhiri permainan.",
  "ch.fraktiot": "Faksi dan susunan awal",
  "p.4.1": "Permainan memiliki empat faksi yang ditempatkan di sudut-sudut papan: Rus di kiri atas, Mongol di kanan atas, Song di kanan bawah, dan Khwarezm di kiri bawah. Pusat peta bersifat netral.",
  "p.4.2": "Setiap faksi memulai dengan 12 provinsi, sebuah ibu kota, dan satu pasukan pendiri yang dipimpin oleh Kepala Suku (Bab XIII). Sumber daya awal dan bonus khusus tercantum di bawah.",
  "t1.h.0": "Faksi",
  "t1.h.1": "Warna",
  "t1.h.2": "Penguasa",
  "t1.h.3": "Ibu kota",
  "t1.h.4": "Emas",
  "t1.h.5": "Tenaga",
  "t1.h.6": "Kuda",
  "t1.h.7": "Bonus khusus",
  "t1.r.0.0": "Kekaisaran Mongol",
  "t1.r.0.1": "🟡 kuning",
  "t1.r.0.2": "Genghis Khan",
  "t1.r.0.3": "Karakorum",
  "t1.r.0.7": "Kavaleri +30%, pengepungan +20% · agresif",
  "t1.r.1.0": "Dinasti Song",
  "t1.r.1.1": "🟢 hijau",
  "t1.r.1.2": "Kaisar Ningzong",
  "t1.r.1.3": "Lin'an (Hangzhou)",
  "t1.r.1.7": "Perpajakan +30%, kavaleri −10%, pengepungan −10% · pedagang",
  "t1.r.2.0": "Kepangeranan Rus",
  "t1.r.2.1": "⚪ abu-abu",
  "t1.r.2.2": "Pangeran Agung",
  "t1.r.2.3": "Novgorod",
  "t1.r.2.7": "Perpajakan +10%, pengepungan +10% · defensif",
  "t1.r.3.0": "Kekaisaran Khwarezm",
  "t1.r.3.1": "🟣 ungu",
  "t1.r.3.2": "Shah Muhammad II",
  "t1.r.3.3": "Samarkand",
  "t1.r.3.7": "Kavaleri +10%, perpajakan +20%, pengepungan +10% · ekspansionis",
  "p.4.3": "Hubungan awal: semua faksi memulai dalam keadaan netral satu sama lain (hubungan 0, kepercayaan 50, ancaman 30). Pengecualian: yang lain memulai dengan kecurigaan bawaan terhadap Mongol (hubungan −20, ancaman 60), karena Mongol adalah kekuatan ekspansionis yang agresif.",
  "p.4.4": "Persediaan awal (dibagikan kepada semua pemain): 10 makanan, 3 perajin, 0 pengaruh, 0 prestise. Tangan awal: 5 kartu (Bab XIV).",
  "ch.kartta": "Peta, provinsi, dan medan",
  "p.5.1": "Peta berupa kisi heks tempat setiap heks penuh memuat satu desa. Desa-desa dibagi antara faksi (tepi/sudut) dan wilayah netral (tengah). Ketetanggaan dihitung dengan tata letak heks odd-r: setiap petak berbatasan dengan paling banyak enam tetangga.",
  "p.5.2": "Medan memengaruhi biaya gerak, pertahanan, batas suplai, dan perpajakan. Biaya gerak bergantung pada jenis unit (infanteri/kavaleri/pengepungan). Bonus pertahanan ditambahkan ke kekuatan tempur pihak bertahan (Bab XI).",
  "t2.h.0": "Medan",
  "t2.h.1": "Infanteri",
  "t2.h.2": "Kavaleri",
  "t2.h.3": "Pengepungan",
  "t2.h.4": "Pertahanan",
  "t2.h.5": "Suplai",
  "t2.h.6": "Pengali pajak",
  "t2.r.0.0": "🌾 Stepa",
  "t2.r.1.0": "🌿 Padang rumput",
  "t2.r.2.0": "🌾 Lahan pertanian",
  "t2.r.3.0": "🌲 Hutan",
  "t2.r.4.0": "⛰️ Perbukitan",
  "t2.r.5.0": "⛰️ Pegunungan",
  "t2.r.6.0": "🏜️ Gurun",
  "t2.r.7.0": "🌿 Rawa",
  "t2.r.8.0": "🌲 Taiga",
  "t2.r.9.0": "❄️ Tundra",
  "p.5.3": "Lahan pertanian dan padang rumput menghasilkan makanan; provinsi stepa dan kuda menghasilkan kuda; lahan pertanian dan perbukitan menghasilkan perajin (Bab VII). Pegunungan dan perbukitan memberi pertahanan terbaik tetapi memperlambat gerak.",
  "ch.vuoro": "Struktur giliran (5 fase)",
  "p.6.1": "Setiap giliran (tahun) berlangsung melalui lima fase dalam urutan tetap. Pindah dari satu fase ke fase berikutnya dengan tombol Berikutnya.",
  "p.6.2": "**1. Sumber daya:** kumpulkan pendapatan dari provinsi yang dikuasai (emas, tenaga manusia, makanan, kuda, perajin) ditambah pengaruh dan prestise. Pendapatan dihitung dengan rumus di Bab VII.",
  "p.6.3": "**2. Kartu:** tarik 1 kartu dari dek (tangan awal adalah 5) dan mainkan kartu apa pun yang Anda inginkan dari tangan Anda. Efek kartu dijelaskan di Bab XIV.",
  "p.6.4": "**3. Serang:** gerakkan pasukan ke provinsi tetangga atau selesaikan serangan terhadap provinsi yang dikuasai musuh atau netral (Bab XI).",
  "p.6.5": "**4. Bangun:** dirikan bangunan di provinsi Anda sendiri dan rekrut pasukan (Bab IX–X).",
  "p.6.6": "**5. Akhiri giliran:** lawan AI melakukan gerakan mereka, pengepungan berlanjut, bonus permanen diperbarui, syarat kemenangan diperiksa, dan tahun baru dimulai.",
  "ch.talous": "Sumber daya dan ekonomi",
  "p.7.1": "**Pendapatan emas** = (pajak dasar provinsi + bonus Jalur Sutra + bonus pasar + bonus jembatan) × pengali ibu kota. Setiap pasar memberi +3 emas, setiap jembatan Jalur Sutra memberi +2 emas. Jika ibu kota hilang, pengalinya 0.5 (pendapatan dibelah dua), jika tidak 1.0.",
  "p.7.2": "**Dorongan awal permainan:** pada giliran 1–4, +4 ditambahkan ke pendapatan emas untuk mempercepat pembangunan awal.",
  "p.7.3": "**Tenaga manusia** = 30% dari total tenaga manusia dasar provinsi (dibulatkan ke bawah).",
  "p.7.4": "**Makanan** = −1 per pasukan (pemeliharaan) + 0.5 × provinsi lahan pertanian/padang rumput + 2 × perkemahan. Makanan dapat berubah negatif; ini dikonsumsi oleh pemeliharaan pasukan.",
  "p.7.5": "**Kuda** = jumlah provinsi stepa/kuda + jumlah kandang kuda (1 per kandang).",
  "p.7.6": "**Perajin** = 0.5 × (provinsi lahan pertanian dan perbukitan) + jumlah bengkel. Jika Anda menguasai setidaknya 3 provinsi, Anda memperoleh setidaknya 1 perajin per giliran.",
  "p.7.7": "**Pengaruh/giliran** = simpul dagang (masing-masing 1) + ibu kota yang dipertahankan (2) + aliansi (masing-masing 2) + Keajaiban (masing-masing 2).",
  "p.7.8": "**Prestise/giliran** = 3 × jumlah Keajaiban.",
  "ch.silkkitie": "Jalur Sutra dan simpul dagang",
  "p.8.1": "Jalur Sutra adalah rute dagang yang melintasi baris tengah peta. Provinsi di sepanjangnya adalah simpul dagang (ditandai dengan bendera Jalur Sutra).",
  "p.8.2": "**Bonus Jalur Sutra** = pajak dasar simpul dagang + 2 × simpul yang menghasilkan barang dagang sutra + **bonus rantai**. Bonus rantai memberi hadiah untuk menguasai deretan simpul tanpa putus: setiap gugus yang saling terhubung (ukuran > 1) memberikan sekitar 1.6 × (ukuran gugus^1.45) emas tambahan. Karena itu, satu bentangan Jalur Sutra yang utuh jauh lebih berharga daripada persinggahan yang terpencar.",
  "p.8.3": "Menguasai mayoritas Jalur Sutra (lebih dari setengah dari semua simpul) adalah syarat Kemenangan Ekonomi (§ 3.3) dan menghasilkan pengaruh yang besar (§ 7.7).",
  "ch.rakennukset": "Bangunan",
  "p.9.1": "Bangunan didirikan selama fase Bangun di provinsi Anda sendiri. Bangunan memerlukan emas dan sering kali juga perajin. Setiap bangunan memberi manfaat permanen.",
  "t3.h.0": "Bangunan",
  "t3.h.1": "Emas",
  "t3.h.2": "Perajin",
  "t3.h.3": "Efek",
  "t3.r.0.0": "⛺ Perkemahan",
  "t3.r.0.3": "+2 makanan/giliran; titik rekrutmen infanteri",
  "t3.r.1.0": "🏪 Pasar",
  "t3.r.1.3": "+3 emas/giliran",
  "t3.r.2.0": "🌉 Jembatan",
  "t3.r.2.3": "+2 emas/giliran di Jalur Sutra; titik penyeberangan kafilah",
  "t3.r.3.0": "🔨 Bengkel",
  "t3.r.3.3": "+1 perajin/giliran; pasukan yang direkrut mendapat +10 moral",
  "t3.r.4.0": "🐎 Kandang Kuda",
  "t3.r.4.3": "+1 kuda/giliran; titik rekrutmen kavaleri",
  "t3.r.5.0": "🏯 Benteng",
  "t3.r.5.3": "+3 pertahanan (menaikkan tingkat fortifikasi)",
  "t3.r.6.0": "🏛️ Keajaiban",
  "t3.r.6.3": "Hanya ibu kota: +prestise dan +pengaruh/giliran",
  "p.9.2": "**Peran bangunan dalam rekrutmen:** Perkemahan membuka rekrutmen infanteri, Kandang Kuda membuka rekrutmen kavaleri. Di ibu kota, keduanya dapat direkrut tanpa bangunan khusus (Bab X).",
  "p.9.3": "**Keajaiban** adalah satu-satunya sumber prestise dan karena itu menjadi kunci Kemenangan Budaya. Bangunan ini hanya dapat dibangun di ibu kota.",
  "ch.armeijat": "Pasukan, rekrutmen, dan pergerakan",
  "p.10.1": "**Biaya rekrutmen:** Infanteri berbiaya **10 emas dan 5 makanan**. Kavaleri berbiaya **20 emas, 5 kuda, dan 10 makanan**.",
  "p.10.2": "**Syarat rekrutmen:** infanteri dapat direkrut dari provinsi yang memiliki Perkemahan (atau dari ibu kota); kavaleri dari provinsi yang memiliki Kandang Kuda (atau dari ibu kota). Jika ibu kota hilang, rekrutmen ditangguhkan sampai ibu kota direbut kembali.",
  "p.10.3": "**Komposisi tumpukan:** satu rekrutmen infanteri menghasilkan 5 infanteri (+ hingga 2 kavaleri tergantung kuda yang tersedia). Satu rekrutmen kavaleri menghasilkan kavaleri sebesar min(4 + kandang, kuda/2), dengan sisanya menjadi infanteri (setidaknya 2). Bengkel memberi pasukan baru +10 moral (moral dasar 70, 80 dengan Bengkel).",
  "p.10.4": "**Pergerakan:** sebuah pasukan bergerak ke provinsi tetangga dengan membayar biaya gerak medannya (Bab V). Unit pengepungan memakai biaya pengepungan; jika tidak, tumpukan yang dominan kavaleri (kavaleri ≥ infanteri) memakai biaya kavaleri, dan tumpukan yang dominan infanteri memakai biaya infanteri.",
  "p.10.5": "**Moral dan suplai:** setiap pasukan memiliki moral (0–100) dan suplai. Pertempuran yang dimenangkan menaikkan moral (+5). Kedekatan dengan Kepala Suku menaikkan moral (Bab XIII).",
  "ch.taistelu": "Sistem pertempuran",
  "p.11.1": "**Kekuatan tempur:** Kekuatan penyerang = 2 × kavaleri + infanteri + pengepungan + bonus serangan. Kekuatan bertahan = 2 × kavaleri + infanteri. Dengan demikian, kavaleri bernilai dua kali lipat dalam kekuatan mentah.",
  "p.11.2": "**Lemparan dadu:** kedua pihak melempar 1d6. Skor penyerang = kekuatan + dadu. Skor bertahan = kekuatan + dadu + 2 × bonus pertahanan medan + 3 × tingkat fortifikasi efektif.",
  "p.11.3": "**Pengepungan melemahkan tembok:** tingkat fortifikasi efektif = tingkat fortifikasi − 0.5 × unit pengepungan (tidak di bawah 0). Jadi unit pengepungan mengikis pertahanan.",
  "p.11.4": "**Penyelesaian:** pihak dengan skor lebih tinggi menang. Jika penyerang menang, pihak bertahan menerima kerusakan (kekuatan penyerang − bonus pertahanan); jika penyerang kalah, penyerang menerima kerusakan sebesar kekuatan pihak bertahan.",
  "p.11.5": "**Alokasi korban:** kerusakan pertama-tama mengenai infanteri; sisa kerusakan menghilangkan kavaleri dengan efektivitas setengah (kavaleri lebih tangguh). Pihak bertahan hancur jika kehilangan semua kavaleri dan infanterinya.",
  "p.11.6": "**Efek kartu:** kartu strategi yang dimainkan dapat memberi bonus serangan, pertahanan, atau gerak, yang ditambahkan ke perhitungan kekuatan (Bab XIV).",
  "ch.piiritys": "Pengepungan dan ibu kota",
  "p.12.1": "**Blokade:** jika sebuah provinsi sepenuhnya dikelilingi tetangga yang dikuasai musuh, provinsi itu menjadi terkepung dan meter pengepungan bertambah dari giliran ke giliran.",
  "p.12.2": "**Efek pengepungan:** jika provinsi memiliki benteng, tingkatnya turun sebesar −1/giliran saat terkepung. Jika tidak ada benteng, pemilik kehilangan 5 emas/giliran (suplai terputus). Meter pengepungan direset begitu blokade terangkat.",
  "p.12.3": "**Ibu kota yang hilang:** jika ibu kota Anda berada di tangan musuh, (a) semua pendapatan emas dibelah dua (§ 7.1) dan (b) rekrutmen ditangguhkan (§ 10.2) sampai ibu kota direbut kembali.",
  "p.12.4": "**Ibu kota musuh** adalah kunci Kemenangan Militer: merebut setiap ibu kota musuh mengakhiri permainan dengan kemenangan (§ 3.2).",
  "ch.paallikko": "Kepala Suku",
  "p.13.1": "Pasukan pendiri setiap faksi (pasukan utama) membawa Kepala Suku. Sang Kepala adalah pemimpin sekaligus sumber moral.",
  "p.13.2": "**Bonus moral:** pasukan di provinsi yang sama dengan Kepala mendapat +5 moral, dan pasukan di provinsi tetangga mendapat bonus yang lebih kecil. Bonus diperbarui pada akhir giliran.",
  "p.13.3": "**Kematian Sang Kepala:** jika pasukan pendiri pemain hancur, ada penalti satu kali: **−30 emas**, **−15 pengaruh**, dan moral semua pasukan pemain turun (−10). Ini hanya terjadi sekali.",
  "p.13.4": "Karena itu, melindungi Sang Kepala penting secara strategis: jangan kirim pasukan pendiri ke risiko yang tidak perlu di awal permainan.",
  "ch.kortit": "Sistem kartu",
  "p.14.1": "**Menarik kartu:** permainan dimulai dengan tangan berisi 5 kartu; selama fase Kartu Anda menarik 1 kartu baru per giliran. Kartu yang dimainkan masuk ke tumpukan buangan (kecuali kartu teknologi permanen).",
  "p.14.2": "**Jenis kartu:** strategi (bonus tempur), teknologi (bonus permanen; 5 kartu dimainkan = Kemenangan Teknologi), diplomasi (hubungan), dan sumber daya (emas/makanan/kuda/perajin).",
  "p.14.3": "**Kelangkaan:** umum, tidak umum, langka, legendaris. Kartu yang lebih langka lebih kuat tetapi muncul lebih jarang.",
  "p.14.4": "**Durasi efek:** kartu sumber daya berlaku segera (emas/makanan/kuda/perajin ditambahkan ke persediaan). Bonus serangan/pertahanan berlangsung selama durasi tertentu (sering kali hanya giliran ini); bonus gerak segera menambah poin gerak. Kartu serangan/pertahanan permanen (teknologi) tetap berlaku selama sisa permainan.",
  "p.14.5": "Kartu muncul dengan ilustrasi di panel kartu di bagian bawah tampilan permainan. Panel dapat diperbesar atau diperkecil dengan menyeret tepi atasnya; kartu selalu diskalakan agar tetap terlihat sepenuhnya.",
  "ch.diplomatia": "Diplomasi",
  "p.15.1": "**Hubungan:** setiap pasangan faksi memiliki skor hubungan, kepercayaan, ancaman, dan gesekan perbatasan. Perjanjian mengubah nilai-nilai ini.",
  "p.15.2": "**Jenis perjanjian:** damai — non-agresi, perdamaian, gencatan senjata, dan aliansi; serta terkait perang — perang formal (war_formal) dan serangan mendadak (war_surprise).",
  "p.15.3": "**Aliansi** menghasilkan +2 pengaruh/giliran (§ 7.7). Aliansi dengan setiap musuh yang masih hidup (setidaknya 2) adalah salah satu jalur menuju Kemenangan Diplomatik (§ 3.5).",
  "p.15.4": "**Deklarasi perang:** perang formal aktif pada giliran yang ditetapkan dan menjatuhkan hubungan (−90) serta kepercayaan (0), sekaligus menaikkan ancaman (+30). Mongol sudah membawa ancaman awal yang lebih tinggi sejak awal (§ 4.3).",
  "ch.kauppa": "Barang dagang",
  "p.16.1": "Sebagian provinsi menghasilkan barang dagang, yang memberi manfaat permanen kepada pemiliknya. Nilai menggambarkan harga relatif barang itu dalam perdagangan.",
  "t4.h.0": "Barang",
  "t4.h.1": "Nilai",
  "t4.h.2": "Efek",
  "t4.r.0.0": "🪙 Emas",
  "t4.r.0.2": "+3 emas/giliran",
  "t4.r.1.0": "🧣 Sutra",
  "t4.r.1.2": "+3 emas/giliran (memperkuat Jalur Sutra)",
  "t4.r.2.0": "💎 Permata",
  "t4.r.2.2": "+2 emas/giliran dan +1 moral",
  "t4.r.3.0": "🌶️ Rempah-rempah",
  "t4.r.3.2": "+2 emas/giliran",
  "t4.r.4.0": "🧥 Bulu",
  "t4.r.4.2": "+1 suplai dan +1 moral",
  "t4.r.5.0": "🐴 Kuda",
  "t4.r.5.2": "+2 rekrutmen kavaleri",
  "t4.r.6.0": "⚔️ Besi",
  "t4.r.6.2": "−20% biaya unit",
  "t4.r.7.0": "🧂 Garam",
  "t4.r.7.2": "+1 suplai",
  "t4.r.8.0": "🌾 Biji-bijian",
  "t4.r.8.2": "+2 tenaga manusia",
  "t4.r.9.0": "🐄 Ternak",
  "t4.r.9.2": "+1 tenaga manusia, +1 suplai",
  "ch.tekoaly": "Kecerdasan buatan (AI)",
  "p.17.1": "Pada akhir giliran, setiap faksi AI bertindak sesuai kepribadiannya: yang agresif (Mongol) berekspansi dan menyerang, yang pedagang (Song) berfokus pada ekonomi, yang defensif (Rus) memperkuat pertahanan, dan yang ekspansionis (Khwarezm) merebut provinsi netral.",
  "p.17.2": "AI dapat menang melalui kemenangan militer atau ekonomi dengan syarat yang sama seperti pemain. Gerakan AI ditampilkan dalam notifikasi akhir giliran.",
  "p.17.3": "AI memperhitungkan skor ancaman dan hubungan: ancaman yang tinggi meningkatkan kemungkinan serangan. Ancaman awal Mongol yang tinggi membuat mereka cenderung menjadi agresor.",
  "ch.strategia": "Kiat strategi",
  "p.18.1": "**Gunakan dorongan awal permainan:** pada giliran 1–4 Anda mendapat +4 emas/giliran. Bangun pasar dan perkemahan sejak awal sebagai fondasi ekonomi dan rekrutmen Anda.",
  "p.18.2": "**Pertahankan Jalur Sutra dalam satu rentang utuh:** bonus rantai (§ 8.2) memberi hadiah yang tidak proporsional pada simpul dagang yang bersebelahan — bangun satu rangkaian utuh alih-alih persinggahan yang terpencar.",
  "p.18.3": "**Lindungi ibu kota dan Sang Kepala:** ibu kota yang hilang membelah dua pendapatan dan menghentikan rekrutmen; kematian Sang Kepala memakan 30 emas dan 15 pengaruh.",
  "p.18.4": "**Pilih jalur kemenangan sejak awal:** bagi Mongol jalur militer itu alami (kavaleri +30%), bagi Song jalur ekonomi dan budaya (perpajakan +30%), bagi Khwarezm ekspansi, dan bagi Rus perang defensif yang menguras musuh.",
  "p.18.5": "**Manfaatkan medan:** bertahanlah di pegunungan dan perbukitan (+3/+2 pertahanan), menyeranglah dengan kavaleri di medan terbuka tempat gerak murah.",
  "p.18.6": "**Unit pengepungan melawan tembok:** bawa unit pengepungan saat menghadapi provinsi berbenteng — unit ini melemahkan tingkat fortifikasi efektif (§ 11.3)."
};

export default translations;
