// Sääntökirjan käännös (pt). Avaimet vastaavat Ohjekirja.tsx:n tr()-kutsuja.
const translations: Record<string, string> = {
  "ui.chapter": "Capítulo",
  "ui.title": "Tales of the Steppe — Livro de Regras",
  "ui.subtitle": "História da Estepe · ano 1206 · artigo por artigo",
  "ui.print": "Imprimir",
  "ui.toGame": "Ir ao jogo",
  "ui.search": "Buscar capítulos…",
  "ui.footer": "Tales of the Steppe — História da Estepe · Livro de Regras · ano 1206",
  "ui.backToTop": "↑ Voltar ao topo",
  "ui.returnToGame": "Voltar ao jogo",
  "ch.johdanto": "Introdução e conceito do jogo",
  "p.1.1": "Tales of the Steppe (História da Estepe) é um jogo de estratégia por turnos ambientado em 1206 d.C. — o momento em que Temüjin foi proclamado Gêngis Khan e os povos da estepe viraram o mundo de cabeça para baixo. O jogador lidera uma das quatro grandes potências e busca a vitória por um de cinco caminhos diferentes (Capítulo III).",
  "p.1.2": "É um jogo para um jogador contra oponentes de IA. Cada ano é um turno, dividido em cinco fases (Capítulo VI). O jogador controla províncias (aldeias), reúne recursos, constrói edifícios, recruta exércitos, joga cartas e conduz diplomacia e guerra.",
  "p.1.3": "Este livro de regras descreve as regras do jogo exatamente como foram implementadas. Os valores numéricos (custos, bônus, limiares) são vinculantes e correspondem à lógica do jogo. Em caso de conflito, o próprio jogo é a autoridade, mas o objetivo é que este livro e o jogo estejam de acordo.",
  "ch.kasitteet": "Conceitos básicos e terminologia",
  "p.2.1": "**Província (aldeia):** um hexágono do mapa. Cada província tem um dono (uma facção ou neutra), terreno, desenvolvimento base, um possível bem comercial e um nível de fortificação.",
  "p.2.2": "**Facção:** um reino jogável. Há quatro facções disponíveis: os Mongóis, Song (China), os principados da Rus e Khwarezm (Pérsia).",
  "p.2.3": "**Recursos:** ouro, comida, cavalos, recrutas e artesãos. Além disso, há dois indicadores de status: influência e prestígio.",
  "p.2.4": "**Influência:** peso diplomático, gerado por nós comerciais, pela posse da capital, por alianças e por Maravilhas. É o medidor da Vitória Diplomática.",
  "p.2.5": "**Prestígio:** renome cultural, gerado apenas por Maravilhas (um tipo de edifício). É o medidor da Vitória Cultural.",
  "p.2.6": "**Exército:** um agrupamento de unidades com cavalaria, infantaria e possivelmente unidades de cerco, além de moral e suprimento.",
  "p.2.7": "**Rota da Seda:** uma rota comercial que atravessa o mapa; as províncias ao longo dela são nós comerciais que geram renda extra e influência (Capítulo VIII).",
  "ch.voitto": "Condições de vitória — cinco caminhos",
  "p.3.1": "O jogo termina em vitória quando qualquer uma das cinco condições a seguir é atendida ao fim do turno de um jogador. As condições são verificadas ao fim de todo turno.",
  "p.3.2": "**Vitória Militar:** capture a capital de cada facção inimiga — OU controle pelo menos **30 províncias** (cerca de 40% do mapa).",
  "p.3.3": "**Vitória Econômica:** três condições ao mesmo tempo: (a) pelo menos **500 de ouro** no tesouro, (b) você controla a **maioria dos nós comerciais da Rota da Seda** (mais da metade) e (c) mantém o limite de ouro por **pelo menos 3 turnos consecutivos** (a sequência reinicia se o ouro cair abaixo de 500).",
  "p.3.4": "**Vitória Tecnológica:** jogue **pelo menos 5 cartas de tecnologia** (cartas permanentes de tecnologia).",
  "p.3.5": "**Vitória Diplomática:** alcance **pelo menos 100 de influência** — OU forme uma aliança com cada facção inimiga sobrevivente (pelo menos 2 aliados).",
  "p.3.6": "**Vitória Cultural:** acumule **pelo menos 60 de prestígio** construindo Maravilhas em sua capital.",
  "p.3.7": "**Derrota:** o jogador perde se perder todas as suas províncias e todos os seus exércitos. A IA também pode vencer por vitória militar ou econômica, o que encerra o jogo.",
  "ch.fraktiot": "Facções e configuração inicial",
  "p.4.1": "O jogo tem quatro facções posicionadas nos cantos do tabuleiro: a Rus no canto superior esquerdo, os Mongóis no canto superior direito, Song no canto inferior direito e Khwarezm no canto inferior esquerdo. O centro do mapa é neutro.",
  "p.4.2": "Cada facção começa com 12 províncias, uma capital e um exército fundador liderado pelo Chefe Tribal (Capítulo XIII). Os recursos iniciais e os bônus especiais estão listados abaixo.",
  "t1.h.0": "Facção",
  "t1.h.1": "Cor",
  "t1.h.2": "Governante",
  "t1.h.3": "Capital",
  "t1.h.4": "Ouro",
  "t1.h.5": "Recrutas",
  "t1.h.6": "Cavalos",
  "t1.h.7": "Bônus especiais",
  "t1.r.0.0": "Império Mongol",
  "t1.r.0.1": "🟡 amarelo",
  "t1.r.0.2": "Gêngis Khan",
  "t1.r.0.3": "Karakorum",
  "t1.r.0.7": "Cavalaria +30%, cerco +20% · agressivo",
  "t1.r.1.0": "Dinastia Song",
  "t1.r.1.1": "🟢 verde",
  "t1.r.1.2": "Imperador Ningzong",
  "t1.r.1.3": "Lin'an (Hangzhou)",
  "t1.r.1.7": "Tributos +30%, cavalaria −10%, cerco −10% · comerciante",
  "t1.r.2.0": "Principados da Rus",
  "t1.r.2.1": "⚪ cinza",
  "t1.r.2.2": "Grão-Príncipe",
  "t1.r.2.3": "Novgorod",
  "t1.r.2.7": "Tributos +10%, cerco +10% · defensivo",
  "t1.r.3.0": "Império de Khwarezm",
  "t1.r.3.1": "🟣 roxo",
  "t1.r.3.2": "Xá Muhammad II",
  "t1.r.3.3": "Samarcanda",
  "t1.r.3.7": "Cavalaria +10%, tributos +20%, cerco +10% · expansionista",
  "p.4.3": "Relações iniciais: todas as facções começam neutras entre si (relação 0, confiança 50, ameaça 30). Exceção: as outras começam com suspeita inerente em relação aos Mongóis (relação −20, ameaça 60), já que os Mongóis são uma potência expansionista agressiva.",
  "p.4.4": "Reserva inicial (igual para todos os jogadores): 10 de comida, 3 artesãos, 0 de influência, 0 de prestígio. Mão inicial: 5 cartas (Capítulo XIV).",
  "ch.kartta": "Mapa, províncias e terreno",
  "p.5.1": "O mapa é uma grade hexagonal na qual cada hexágono completo contém uma aldeia. As aldeias são divididas entre as facções (bordas/cantos) e os neutros (centro). A adjacência é calculada com um layout hexagonal odd-r: cada peça faz fronteira com no máximo seis vizinhos.",
  "p.5.2": "O terreno afeta o custo de movimento, a defesa, o limite de suprimento e a tributação. O custo de movimento depende do tipo de unidade (infantaria/cavalaria/cerco). O bônus de defesa é somado ao poder de combate do defensor (Capítulo XI).",
  "t2.h.0": "Terreno",
  "t2.h.1": "Infantaria",
  "t2.h.2": "Cavalaria",
  "t2.h.3": "Cerco",
  "t2.h.4": "Defesa",
  "t2.h.5": "Suprimento",
  "t2.h.6": "Multiplicador de impostos",
  "t2.r.0.0": "🌾 Estepe",
  "t2.r.1.0": "🌿 Pradaria",
  "t2.r.2.0": "🌾 Terras agrícolas",
  "t2.r.3.0": "🌲 Floresta",
  "t2.r.4.0": "⛰️ Colinas",
  "t2.r.5.0": "⛰️ Montanhas",
  "t2.r.6.0": "🏜️ Deserto",
  "t2.r.7.0": "🌿 Pântano",
  "t2.r.8.0": "🌲 Taiga",
  "t2.r.9.0": "❄️ Tundra",
  "p.5.3": "Terras agrícolas e pradarias produzem comida; províncias de estepe e de cavalos produzem cavalos; terras agrícolas e colinas produzem artesãos (Capítulo VII). Montanhas e colinas oferecem a melhor defesa, mas retardam o movimento.",
  "ch.vuoro": "Estrutura do turno (5 fases)",
  "p.6.1": "Cada turno (ano) passa por cinco fases em ordem fixa. Passe de uma fase para a seguinte com o botão \"Próximo\".",
  "p.6.2": "**1. Recursos:** colete a renda das províncias controladas (ouro, recrutas, comida, cavalos, artesãos), além de influência e prestígio. A renda é calculada com as fórmulas do Capítulo VII.",
  "p.6.3": "**2. Cartas:** compre 1 carta do baralho (a mão inicial é 5) e jogue as cartas que quiser da sua mão. Os efeitos das cartas estão no Capítulo XIV.",
  "p.6.4": "**3. Ataque:** mova exércitos para províncias vizinhas ou resolva ataques contra províncias controladas por inimigos ou neutros (Capítulo XI).",
  "p.6.5": "**4. Construção:** construa edifícios em suas próprias províncias e recrute tropas (Capítulos IX–X).",
  "p.6.6": "**5. Fim do turno:** os oponentes de IA fazem seus movimentos, os cercos avançam, os bônus permanentes são atualizados, as condições de vitória são verificadas e um novo ano começa.",
  "ch.talous": "Recursos e economia",
  "p.7.1": "**Renda de ouro** = (imposto base das províncias + bônus da Rota da Seda + bônus de mercado + bônus de ponte) × multiplicador da capital. Cada mercado rende +3 de ouro, cada ponte da Rota da Seda rende +2 de ouro. Se a capital for perdida, o multiplicador é 0.5 (renda reduzida à metade), caso contrário 1.0.",
  "p.7.2": "**Impulso do início de jogo:** nos turnos 1–4, +4 é adicionado à renda de ouro para acelerar as construções iniciais.",
  "p.7.3": "**Recrutas** = 30% da mão de obra base combinada das províncias (arredondado para baixo).",
  "p.7.4": "**Comida** = −1 por exército (manutenção) + 0.5 × províncias de terras agrícolas/pradaria + 2 × acampamentos. A comida pode ter variação negativa; ela é consumida pela manutenção das tropas.",
  "p.7.5": "**Cavalos** = número de províncias de estepe/cavalos + número de estábulos (1 por estábulo).",
  "p.7.6": "**Artesãos** = 0.5 × (províncias de terras agrícolas e colinas) + número de oficinas. Se você controlar pelo menos 3 províncias, recebe pelo menos 1 artesão por turno.",
  "p.7.7": "**Influência/turno** = nós comerciais (1 cada) + capital mantida (2) + alianças (2 cada) + Maravilhas (2 cada).",
  "p.7.8": "**Prestígio/turno** = 3 × número de Maravilhas.",
  "ch.silkkitie": "A Rota da Seda e os nós comerciais",
  "p.8.1": "A Rota da Seda é uma rota comercial que percorre a fileira central do mapa. As províncias ao longo dela são nós comerciais (marcados com uma bandeira da Rota da Seda).",
  "p.8.2": "**Bônus da Rota da Seda** = imposto base dos nós comerciais + 2 × nós que produzem o bem comercial seda + **bônus de cadeia**. O bônus de cadeia recompensa o controle de sequências ininterruptas de nós: cada agrupamento conectado (tamanho > 1) concede cerca de 1.6 × (tamanho do agrupamento^1.45) de ouro extra. Assim, um único trecho contínuo da Rota da Seda vale muito mais do que paradas dispersas.",
  "p.8.3": "Controlar a maioria da Rota da Seda (mais da metade de todos os nós) é um requisito para a Vitória Econômica (§ 3.3) e gera influência significativa (§ 7.7).",
  "ch.rakennukset": "Edifícios",
  "p.9.1": "Os edifícios são construídos durante a fase de Construção em suas próprias províncias. Eles custam ouro e muitas vezes artesãos. Cada edifício concede um benefício permanente.",
  "t3.h.0": "Edifício",
  "t3.h.1": "Ouro",
  "t3.h.2": "Artesãos",
  "t3.h.3": "Efeito",
  "t3.r.0.0": "⛺ Acampamento",
  "t3.r.0.3": "+2 comida/turno; ponto de recrutamento de infantaria",
  "t3.r.1.0": "🏪 Mercado",
  "t3.r.1.3": "+3 ouro/turno",
  "t3.r.2.0": "🌉 Ponte",
  "t3.r.2.3": "+2 ouro/turno na Rota da Seda; ponto de travessia de caravanas",
  "t3.r.3.0": "🔨 Oficina",
  "t3.r.3.3": "+1 artesão/turno; tropas recrutadas recebem +10 de moral",
  "t3.r.4.0": "🐎 Estábulo",
  "t3.r.4.3": "+1 cavalo/turno; ponto de recrutamento de cavalaria",
  "t3.r.5.0": "🏯 Fortaleza",
  "t3.r.5.3": "+3 defesa (aumenta o nível de fortificação)",
  "t3.r.6.0": "🏛️ Maravilha",
  "t3.r.6.3": "Somente na capital: +prestígio e +influência/turno",
  "p.9.2": "**Papel dos edifícios no recrutamento:** um Acampamento desbloqueia o recrutamento de infantaria, um Estábulo desbloqueia o recrutamento de cavalaria. Na capital, ambos podem ser recrutados sem um edifício dedicado (Capítulo X).",
  "p.9.3": "**Maravilha** é a única fonte de prestígio e, portanto, a chave para a Vitória Cultural. Ela só pode ser construída na capital.",
  "ch.armeijat": "Exércitos, recrutamento e movimento",
  "p.10.1": "**Custos de recrutamento:** a Infantaria custa **10 de ouro e 5 de comida**. A Cavalaria custa **20 de ouro, 5 cavalos e 10 de comida**.",
  "p.10.2": "**Requisitos de recrutamento:** a infantaria pode ser recrutada em uma província com um Acampamento (ou a capital); a cavalaria, em uma província com um Estábulo (ou a capital). Se a capital for perdida, o recrutamento fica suspenso até ser retomada.",
  "p.10.3": "**Composição do agrupamento:** um recrutamento de infantaria produz 5 de infantaria (+ até 2 de cavalaria dependendo dos cavalos disponíveis). Um recrutamento de cavalaria produz cavalaria igual a min(4 + estábulos, cavalos/2), com o restante vindo como infantaria (pelo menos 2). Uma Oficina concede +10 de moral às novas tropas (moral base 70, 80 com uma Oficina).",
  "p.10.4": "**Movimento:** um exército move-se para uma província vizinha pagando o custo de movimento do terreno (Capítulo V). Unidades de cerco usam o custo de cerco; caso contrário, um agrupamento com predominância de cavalaria (cavalaria ≥ infantaria) usa o custo de cavalaria, e agrupamentos com predominância de infantaria usam o custo de infantaria.",
  "p.10.5": "**Moral e suprimento:** todo exército tem moral (0–100) e suprimento. Uma batalha vitoriosa aumenta a moral (+5). A proximidade do Chefe Tribal aumenta a moral (Capítulo XIII).",
  "ch.taistelu": "Sistema de batalha",
  "p.11.1": "**Poder de combate:** poder do atacante = 2 × cavalaria + infantaria + cerco + bônus de ataque. Poder do defensor = 2 × cavalaria + infantaria. Assim, a cavalaria vale o dobro em poder bruto.",
  "p.11.2": "**Rolagem de dado:** ambos os lados rolam 1d6. Pontuação do atacante = poder + dado. Pontuação do defensor = poder + dado + 2 × bônus de defesa do terreno + 3 × nível efetivo de fortificação.",
  "p.11.3": "**O cerco enfraquece as muralhas:** nível efetivo de fortificação = nível de fortificação − 0.5 × unidades de cerco (não abaixo de 0). Assim, unidades de cerco corroem a defesa.",
  "p.11.4": "**Resolução:** quem tiver a pontuação mais alta vence. Se o atacante vencer, o defensor sofre dano (poder do atacante − bônus de defesa); se o atacante perder, o atacante sofre dano igual ao poder do defensor.",
  "p.11.5": "**Alocação de baixas:** o dano atinge primeiro a infantaria; qualquer dano restante remove cavalaria com meia eficácia (a cavalaria é mais resistente). O defensor é destruído se perder toda a sua cavalaria e toda a sua infantaria.",
  "p.11.6": "**Efeitos das cartas:** cartas de estratégia jogadas podem conceder bônus de ataque, defesa ou movimento, que são somados ao cálculo de poder (Capítulo XIV).",
  "ch.piiritys": "Cerco e capitais",
  "p.12.1": "**Bloqueio:** se uma província estiver completamente cercada por vizinhos controlados pelo inimigo, ela fica sitiada e o medidor de cerco cresce turno a turno.",
  "p.12.2": "**Efeito do cerco:** se a província tiver uma fortaleza, seu nível cai em −1/turno sob cerco. Se não houver fortaleza, o dono perde 5 ouro/turno (o suprimento é cortado). O medidor de cerco é zerado quando o bloqueio é rompido.",
  "p.12.3": "**Capital perdida:** se sua própria capital estiver nas mãos do inimigo, (a) toda a renda de ouro é reduzida à metade (§ 7.1) e (b) o recrutamento é suspenso (§ 10.2) até a capital ser retomada.",
  "p.12.4": "**Capitais inimigas** são a chave para a Vitória Militar: capturar cada capital inimiga encerra o jogo em vitória (§ 3.2).",
  "ch.paallikko": "Chefe Tribal",
  "p.13.1": "O exército fundador de cada facção (o exército \"principal\") leva consigo o Chefe Tribal. O Chefe é ao mesmo tempo líder e fonte de moral.",
  "p.13.2": "**Bônus de moral:** exércitos na mesma província que o Chefe ganham +5 de moral, e exércitos em províncias vizinhas recebem um bônus menor. Os bônus são atualizados ao fim do turno.",
  "p.13.3": "**Morte do Chefe:** se o exército fundador do jogador for destruído, segue-se uma penalidade única: **−30 ouro**, **−15 influência** e a moral de todas as tropas do jogador cai (−10). Isso acontece apenas uma vez.",
  "p.13.4": "Proteger o Chefe é, portanto, estrategicamente importante: não envie o exército fundador para riscos desnecessários logo no início.",
  "ch.kortit": "Sistema de cartas",
  "p.14.1": "**Compra de cartas:** o jogo começa com uma mão de 5 cartas; durante a fase de Cartas você compra 1 nova carta por turno. As cartas jogadas vão para a pilha de descarte (exceto as cartas permanentes de tecnologia).",
  "p.14.2": "**Tipos de carta:** estratégia (bônus de combate), tecnologia (bônus permanentes; 5 jogadas = Vitória Tecnológica), diplomacia (relações) e recurso (ouro/comida/cavalos/artesãos).",
  "p.14.3": "**Raridades:** comum, incomum, rara, lendária. Cartas mais raras são mais poderosas, mas aparecem com menos frequência.",
  "p.14.4": "**Duração dos efeitos:** cartas de recurso têm efeito imediato (ouro/comida/cavalos/artesãos são adicionados aos estoques). Bônus de ataque/defesa duram por uma duração definida (muitas vezes apenas este turno); um bônus de movimento adiciona pontos de movimento imediatamente. Cartas permanentes de ataque/defesa (tecnologia) permanecem em efeito pelo resto do jogo.",
  "p.14.5": "As cartas aparecem ilustradas no painel de cartas na parte inferior da visão de jogo. O painel pode ser ampliado ou reduzido arrastando sua borda superior; as cartas sempre se ajustam para permanecer totalmente visíveis.",
  "ch.diplomatia": "Diplomacia",
  "p.15.1": "**Relações:** cada par de facções tem uma pontuação de relação, confiança, ameaça e atrito fronteiriço. Os tratados alteram esses valores.",
  "p.15.2": "**Tipos de tratado:** pacíficos — não agressão, paz, trégua e aliança; e ligados à guerra — guerra formal (war_formal) e ataque surpresa (war_surprise).",
  "p.15.3": "**Aliança** gera +2 influência/turno (§ 7.7). Uma aliança com cada inimigo sobrevivente (pelo menos 2) é um dos caminhos para a Vitória Diplomática (§ 3.5).",
  "p.15.4": "**Declaração de guerra:** uma guerra formal é ativada em um turno definido e derruba as relações (−90) e a confiança (0), além de aumentar a ameaça (+30). Os Mongóis já carregam uma ameaça inicial mais alta desde o começo (§ 4.3).",
  "ch.kauppa": "Bens comerciais",
  "p.16.1": "Algumas províncias produzem um bem comercial, que concede um benefício permanente ao seu dono. O valor descreve a importância relativa do bem no comércio.",
  "t4.h.0": "Bem",
  "t4.h.1": "Valor",
  "t4.h.2": "Efeito",
  "t4.r.0.0": "🪙 Ouro",
  "t4.r.0.2": "+3 ouro/turno",
  "t4.r.1.0": "🧣 Seda",
  "t4.r.1.2": "+3 ouro/turno (fortalece a Rota da Seda)",
  "t4.r.2.0": "💎 Gemas",
  "t4.r.2.2": "+2 ouro/turno e +1 moral",
  "t4.r.3.0": "🌶️ Especiarias",
  "t4.r.3.2": "+2 ouro/turno",
  "t4.r.4.0": "🧥 Peles",
  "t4.r.4.2": "+1 suprimento e +1 moral",
  "t4.r.5.0": "🐴 Cavalos",
  "t4.r.5.2": "+2 ao recrutamento de cavalaria",
  "t4.r.6.0": "⚔️ Ferro",
  "t4.r.6.2": "−20% no custo das unidades",
  "t4.r.7.0": "🧂 Sal",
  "t4.r.7.2": "+1 suprimento",
  "t4.r.8.0": "🌾 Grão",
  "t4.r.8.2": "+2 recrutas",
  "t4.r.9.0": "🐄 Gado",
  "t4.r.9.2": "+1 recruta, +1 suprimento",
  "ch.tekoaly": "Inteligência artificial (IA)",
  "p.17.1": "Ao fim de um turno, cada facção de IA age de acordo com sua personalidade: a agressiva (Mongóis) expande e ataca, a comerciante (Song) foca na economia, a defensiva (Rus) se fortalece, e a expansionista (Khwarezm) toma províncias neutras.",
  "p.17.2": "A IA pode vencer por vitória militar ou econômica sob as mesmas condições do jogador. Os movimentos da IA são mostrados nas notificações de fim de turno.",
  "p.17.3": "A IA leva em conta os valores de ameaça e relação: ameaça alta aumenta a probabilidade de ataque. A alta ameaça inicial dos Mongóis faz deles um agressor provável.",
  "ch.strategia": "Dicas de estratégia",
  "p.18.1": "**Use o impulso do início de jogo:** nos turnos 1–4 você recebe +4 ouro/turno. Construa mercados e acampamentos cedo como base para sua economia e recrutamento.",
  "p.18.2": "**Mantenha a Rota da Seda em um trecho contínuo:** o bônus de cadeia (§ 8.2) recompensa nós comerciais adjacentes de forma desproporcional — construa uma sequência contínua em vez de paradas dispersas.",
  "p.18.3": "**Proteja sua capital e seu Chefe:** uma capital perdida reduz a renda à metade e interrompe o recrutamento; a morte do Chefe custa 30 ouro e 15 influência.",
  "p.18.4": "**Escolha cedo seu caminho de vitória:** para os Mongóis, o caminho militar é natural (cavalaria +30%), para Song os caminhos econômico e cultural (tributos +30%), para Khwarezm a expansão, e para a Rus uma guerra defensiva de desgaste.",
  "p.18.5": "**Use o terreno:** defenda-se em montanhas e colinas (+3/+2 defesa), ataque com cavalaria em terreno aberto, onde o movimento é barato.",
  "p.18.6": "**Unidades de cerco contra muralhas:** leve unidades de cerco contra províncias fortificadas — elas enfraquecem o nível efetivo de fortificação (§ 11.3)."
};

export default translations;
